### ISSUE TITLE
Build CTK with already installed VTK

### ISSUE THREAD

**Issue by wwAngzzx** [commontk/CTK#1037]
My configuration: **QT5.14.2 /VS2019 MSCV 2017x64/VTK 8.2/CMake3.18.0**.  I added the path of VTK_DIR and CTKData_DIR in CMake by adding entry. I also selected **CTK_LlB_VisualizationVTKICore**、**CTK_LIB_Visualization/VTKWidgets**、**CTK_LIB_Visualization/VTK/Widgets_USE_TRANSFER_FUNCTION** and **CTK_USE_SYSTEM_VTK** during the configure process. **The following error occurred when I generated ALL_BUILD in VS**. I wonder if this is a version issue, how can I solve this problem. I want to use CTK for volume rendering in Qt.Hope someone here can help me ！
![image](https://user-images.githubusercontent.com/112041948/186696948-f2bc05ac-c149-4381-9f36-9adf9af160a2.png)
![image](https://user-images.githubusercontent.com/112041948/186697091-da3111bc-3794-4464-96a7-93726f2d518a.png)
![image](https://user-images.githubusercontent.com/112041948/186697178-45c065ce-a436-462e-931d-15ae7f69e53c.png)

**Comment by lassoan** [comment]
I don't see any error messages. Maybe they are in Chinese. To get help, please copy here the full build log (not screenshots). I don't think any CTK maintainer speak Chinese, so either translate the messages or build using English Visual Studio IDE and build tools.

**Comment by lassoan** [comment]
This was helpful. It seems that you tried to build CTK with VTK-8.x or earlier (which does s not support PBR). Current CTK version is only compatible with VTK-9.x or later. You can either upgrade your VTK or use an older CTK version.

**Comment by wwAngzzx** [comment]
Thanks a lot！That's great. I think the suggestion makes sense. I will try it again.But I wonder where can I download the older version of CTK and what version might be appropriate？ I'll be looking forward to your next answer. @lassoan

**Comment by lassoan** [comment]
You can check the revision history of the file that fails to complete to see which commit introduced the commit that made CTK incompatible and use any version before that.
