### ISSUE TITLE
Failed to obtain dependence path of CTKTesting

### ISSUE THREAD

**Issue by HBing110** [commontk/CTK#1039]
CMake Error at CMake/ctkMacroValidateBuildOptions.cmake:138 (message):
  Failed to obtain dependence path of CTKTesting.

  1

  E:/hb/ctk/CTK-master/build-x64

  E:/hb/ctk/CTK-master/build-x64/Utilities/DGraph/Debug/DGraph.exe

  Error in file
  'E:/hb/ctk/CTK-master/build-x64/DGraphInput-alldep-withext.txt' - First
  line should look like: <#Vertices> <#Edges>

  Usage: E:/hb/ctk/CTK-master/build-x64/Utilities/DGraph/Debug/DGraph.exe
  <graphfile> [-paths Label | -sort Label]

Call Stack (most recent call first):
  CMakeLists.txt:864 (ctkMacroValidateBuildOptions)

**Comment by lassoan** [comment]
What is the content of the file `'E:/hb/ctk/CTK-master/build-x64/DGraphInput-alldep-withext.txt`?

**Comment by lassoan** [comment]
Since there was no response to the question, I assume the problem was resolved.
