### ISSUE TITLE
Python completer can display warnings and errors in the console

### ISSUE THREAD

**Issue by lassoan** [commontk/CTK#1054]
This is a follow-up to the problem described in https://github.com/commontk/CTK/pull/1051#pullrequestreview-1164299439

>  from a user standpoint I might be questioning if I'm doing something wrong now that these errors are more prominently displayed

The error messages are reported if a property getter of a Python-wrapped Qt object reports an error (see for example a freshly created `slicer.qMRMLTableView()`, without setting a table node in it).

This is because the auto-completer calls `ctkAbstractPythonManager::dir_object` function, to get a list of attribute names and values. The values are used to determine if the value is "callable" and if it is then `()` is added to the completion.

Potential solutions:
1. change all Qt-wrapped classes in Slicer to not return errors in property getters
2. change the auto-completer to get the list of attribute names and determine if they are callable without executing the getter function for each property

**Comment by jcfr** [comment]
> change all Qt-wrapped classes in Slicer to not return errors in property getters

Considering that independently of `ctkAbstractPythonManager::dir_object`, calling `dir()` on an instance of `qMRMLTableView` returns errors, this would make sense.

```
>>> t = slicer.qMRMLTableView()

>>> dir(t)
['AboveItem', ..., 'windowTitleChanged', 'windowType', 'wordWrap', 'x', 'y']
^ qMRMLTableView:: bool qMRMLTableView::transposed() const  failed: invalid node
^ qMRMLTableView:: bool qMRMLTableView::firstRowLocked() const  failed: invalid node
^ qMRMLTableView:: bool qMRMLTableView::firstColumnLocked() const  failed: invalid node

>>> t.transposed
False
^ qMRMLTableView:: bool qMRMLTableView::transposed() const  failed: invalid node
```

**Comment by lassoan** [comment]
I have a prototype for temporarily disabling error logging during ctkPythonConsoleCompleter's update method (will send a pull request today or tomorrow).

I think Jupyter uses static analysis for getting completions, and that does not execute the property getter methods, so should not log any errors.
