### ISSUE TITLE
Follow symlinks when indexing dicom

### ISSUE THREAD

**Issue by pieper** [commontk/CTK#1065]
I would like to add `QDirIterator::FollowSymlinks` to the `QDirIterator` flags here:

https://github.com/commontk/CTK/blob/master/Libs/DICOM/Core/ctkDICOMIndexer.cpp#L167

This came up when I was creating a subset of a large dicom dataset by symlinking patient folders into a new directory for indexing, but it did not work due to this issue and I needed to make copies instead.  I don't see any downsides to this flag.

I'll add a PR for this.

**Comment by lassoan** [comment]
It makes sense. To allow preserving the current behavior, it would be nice if you could add a flag to enable/disable it. It can be enabled by default.

**Comment by pieper** [comment]
That sounds good.  I'll make it a class property for now and in the future we could decide if we want to expose it in the GUI.

**Comment by lassoan** [comment]
I agree, there is no need to expose this new property on the GUI. Custom applications that care about following or not following the symlinks can easily access the indexer object and change the property as needed.
