### ISSUE TITLE
CTK API Documentation hyperlink on commontk.org

### ISSUE THREAD

**Issue by PaulMartinMurphy** [commontk/CTK#1069]
Hi, 

The hyperlink to the CTK "API Documentation" from the bottom of the commontk.org web page does not point to a valid location (see below). 

Is there somewhere else the API Documentation is available?

Thanks,
-Paul

![image](https://user-images.githubusercontent.com/6519417/222873947-1cde9098-ac23-4f8f-9839-cd60aa5f85ae.png)

![image](https://user-images.githubusercontent.com/6519417/222873918-f081a9bf-e168-4543-b778-93e31936ad0d.png)

**Comment by lassoan** [comment]
This issue has been open for a good while now - see https://github.com/commontk/CTK/issues/937

I see you have already commented there, which will bump the issue. I'm closing this issue now to reduce clutter.
