### ISSUE TITLE
vtk compatibility issue

### ISSUE THREAD

**Issue by alundilong** [commontk/CTK#1075]
I was creating a plugin by following the given examples. Everything went very well until I introduced a vtkOjbect, such as vtkSphere in the code. The plugin complied through(of course, compatible libs of vtk were placed in .pro file), but it's loading failed. 
![image](https://user-images.githubusercontent.com/24465615/227498882-064c3d28-83a0-44e9-b717-9b978e79741a.png)

Here is the piece of code introducing vtkSphereSource:
```c++
// MainWindow
class EscopeTBMainWindowImpl : public QObject, public EscopeTBUIService
{
    Q_OBJECT
    Q_INTERFACES(EscopeTBUIService)

public:
    void createUserInterface() Q_DECL_OVERRIDE {
        vtkNew<vtkSphereSource> sphere;
    }
};
```

**Comment by lassoan** [comment]
Make sure the VTK .dll files are in the same folder as your .exe file.
