### ISSUE TITLE
Using upstream PythonQt

### ISSUE THREAD

**Issue by pandas-a11y-11** [commontk/CTK#1102]
It it currently possible to build CTK using upstream PythonQt? CTK seems to fail to even detect the current version in the system. What changes would ensuring compatibility entail?

**Comment by lassoan** [comment]
[MeVisLab's PythonQt](https://github.com/MeVisLab/pythonqt) cannot be directly used in any CMake-based projects, because it does not support CMake at all. This repository is the upstream repository for CMake-ified PythonQt.

**Comment by jcfr** [comment]
The version of PythonQt used in CTK is now documented in https://github.com/commontk/ctk#supported-qt-versions
