### ISSUE TITLE
When can CTK support qt6.X？

### ISSUE THREAD

**Issue by HBing110** [commontk/CTK#1137]
When can CTK support qt6.X？

**Comment by pieper** [comment]
Some parts of CTK can probably work as-is, but some of us are waiting for PythonQt support before putting much effort into it.
See: https://github.com/MeVisLab/pythonqt/issues/13

**Comment by mingweiLIU** [comment]
Hi, since pythonqt now supports qt6, what about the CTK?

**Comment by pieper** [comment]
I'm curious too - maybe @jcfr or @jamesobutler can give an estimate?

**Comment by lassoan** [comment]
As car as I know, CTK can already support it. Maybe there are a few things PythonQt that need to be sorted out. It will all be finished in a couple of weeks when Slicer starts supporting Qt6.
