### ISSUE TITLE
Multiple plugins publishing and one  plugin subscribing

### ISSUE THREAD

**Issue by HBing110** [commontk/CTK#1139]
Multiple plugins publishing the same topic at the same time, and one plugin subscribing to the same topic may receive incorrect data, which may result in data from the same plugin being received multiple times?

Is it a subscription Plugin that cannot receive multiple asynchronous messages at the same time？

**Comment by jcfr** [comment]
Thanks for reporting this issue and #1138, to help the community of CTK developers better understand the problems, could you update the issues to include steps to reproduce and link to minimal code example illustrating the problem ?

**Comment by HBing110** [comment]
Because there are pictures to illustrate, find a solution
http://t.csdn.cn/7BBeG
