### ISSUE TITLE
CMAKE_INSTALL_PREFIX Not work on new Version

### ISSUE THREAD

**Issue by haipengyu1013** [commontk/CTK#1145]
I git clone the new source code, and compiled it a success. I change CMAKE_INSTALL_PREFIX to another folder path, but not work. only install some cmake files.
I checked the SuperBuild.cmake, the parameter INSTALL_COMMAND  value is null. 

Changed the value into ${_INSTALL_CMD} can fix this issue.

**Comment by jcfr** [comment]
> I git clone the new source code, and compiled it a success.

This is great

>  I change CMAKE_INSTALL_PREFIX to another folder path, but not work. only install some cmake files.

Re-configuring the top-level CTK project by changing the value associated with `CMAKE_INSTALL_PREFIX` will propagate its value to the inner build project.

To illustrate what I mean by `inner-build` and `top-level` directories:

```
C:\tmp\CTK                  # source directory
C:\tmp\CTK-build            # top-level build directory 
C:\tmp\CTK-build\CTK-build  # inner-build directory
```

After installing the inner-build project, CMake modules, libraries and header files are expected to be installed:

For example, on Linux:
```
$ cd /tmp/CTK-build/CTK-build
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=/tmp/CTK-install-test .
$ make install
Install the project...
-- Install configuration: "Release"
-- Installing: /tmp/CTK-install-test/lib/ctk-0.1/CMake/ctkListToString.cmake
-- Installing: /tmp/CTK-install-test/lib/ctk-0.1/CMake/ctkMacroParseArguments.cmake
-- Installing: /tmp/CTK-install-test/lib/ctk-0.1/CMake/ctkMacroSetPaths.cmake
-- Installing: /tmp/CTK-install-test/lib/ctk-0.1/CMake/ctkMacroListFilter.cmake
[...]
-- Installing: /tmp/CTK-install-test/lib/ctk-0.1/libCTKCore.so.0.1.0
-- Installing: /tmp/CTK-install-test/lib/ctk-0.1/libCTKCore.so.0.1
-- Set runtime path of "/tmp/CTK-install-test/lib/ctk-0.1/libCTKCore.so.0.1.0" to ""
-- Installing: /tmp/CTK-install-test/lib/ctk-0.1/libCTKCore.so
[...]
-- Installing: /tmp/CTK-install-test/lib/ctk-0.1/CMake/CTKPluginUseFile.cmake
-- Installing: /tmp/CTK-install-test/lib/ctk-0.1/CMake/CTKExports.cmake
-- Installing: /tmp/CTK-install-test/lib/ctk-0.1/CMake/CTKExports-release.cmake
-- Installing: /tmp/CTK-install-test/lib/ctk-0.1/CMake/CTKConfig.cmake
-- Installing: /tmp/CTK-install-test/lib/ctk-0.1/CMake/CTKConfigVersion.cmake
```

**Comment by jcfr** [comment]
Then assuming you built CTK with Widgets library enabled.

You could do the following to build a small application (using `ctkMatrixWidget`)  against an installed tree of CTK:

* `CMakeLists.txt`:

  ```cmake
  cmake_minimum_required(VERSION 3.0)
  project(Test)
  
  find_package(CTK REQUIRED)
  find_package(Qt5 COMPONENTS ${CTK_QT5_COMPONENTS} REQUIRED)
  
  add_executable(test main.cpp)
  target_link_libraries(test
    Qt5::Widgets
    CTKWidgets
    )
  target_include_directories(test PRIVATE ${CTK_INCLUDE_DIRS})
  ```


* `main.cpp`:

  ```cpp
  // Qt includes
  #include <QApplication>
  
  // CTK includes
  #include <ctkMatrixWidget.h>
  
  int main(int argc, char* argv[])
  {
    QApplication app(argc, argv);
  
    ctkMatrixWidget widget;
    widget.show();
  
    return app.exec();
  }
  ```

Then to run the application:

```
LD_LIBRARY_PATH="/home/jcfr/Support/Qt/5.15.2/gcc_64/lib/:/tmp/CTK-install-test/lib/ctk-0.1/" ./test
```

<img width=50% src="https://github.com/commontk/CTK/assets/219043/a0a06e8e-54a4-4722-abe3-0449b77f7100"/>

**Comment by jcfr** [comment]
Please, re-open another issue if you still have problem.
