### ISSUE TITLE
CTK：生成插件时，需要第三方库opencv 或者oNNXRuntime时，生成插件失败，如何解决？

### ISSUE THREAD

**Issue by wangjy-123** [commontk/CTK#1152]
CTK：生成插件时，需要第三方库opencv 或者oNNXRuntime时，生成插件失败，如何解决？
NMAKE:-1: error: U1073: 不知道如何生成“\”
NMAKE:-1: error: U1077: “D:\Tool\VisualStudioIDE\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\nmake.exe”: 返回代码“0x2”

**Comment by jcfr** [comment]
Thanks for the report.

To ensure the CTK community can assist you, would it be possible to create a new report written in English with additional details providing details for reproducing the problem.

In the meantime, I will be closing this issue.
