### ISSUE TITLE
ctkRangeWidget, ctkDoubleRangeSlider setValue(), setRange() issues

### ISSUE THREAD

**Issue by HarryDC** [commontk/CTK#1157]
I don't know if these are related or not but in implementing the Gui wrapping for the `ctkDoubleRangeSlider` the following issues have come up. `ctkDoubleRangeSlider` does not expose `setRange` in python 

But both the `ctkRangeWidget` and the `ctkDoubleRangeSlider` expose the `setValues` method this method though doesn't seem to accept negative values, e.g in testing when calling `setValue(-1, 10)` the range would result in [0,10]. The `ctkRangeWidget::setRange()` does support ranges on the negative side, but neither `setValue()` function does

From the documentation it is hard to tell the difference between the `setValues` and the `setRange` function

**Comment by jcfr** [comment]
> From the documentation it is hard to tell the difference between the setValues and the setRange function

This should help clarify:

```
Range(minimum)                                          Range(maximum)
  |                                                         |
  |---------------------------------------------------------|
            |                                   |
      min_value (left slider)         max_value (right slider)
```

A range slider has two sliders ("left" and "right") and the functions `minimumValue()` and `maximumValue()` allow to get these.
