### ISSUE TITLE
想问这个框架许可证的情况

### ISSUE THREAD

**Issue by TSMX315** [commontk/CTK#1207]
请问，这个框架开源软件许可证是GPL还是LGPL的。

**Comment by lassoan** [comment]
Github does not have a built-in automatic translator. Please update the issue to include English translation.

**Comment by TSMX315** [comment]
> Github does not have a built-in automatic translator. Please update the issue to include English translation.
In my Qt project, I have utilized the CTK framework, and I am aware that CTK's license protocol is based on the Apache License 2.0. Now, I would like to determine if there are modules within the CTK framework that are based on other licenses, such as GPL or LGPL. Where can I find this information? Or do you happen to know the answer and could inform me directly?

**Comment by lassoan** [comment]
Entire CTK uses Apache - https://github.com/commontk/CTK?tab=Apache-2.0-1-ov-file
