### ISSUE TITLE
Not working documentation

### ISSUE THREAD

**Issue by mdziczkowski** [commontk/CTK#1220]
Some links in the wiki to the documentation aren't working and some return the 404 (Not Found) error.

Could that get fixed asap? Thanks

**Comment by lassoan** [comment]
The documentation just exposes contents of .h files, so there is no urgency, you can still access all information.

Of course, it would be nicer and more convenient to use standard doxygen-generated webpages. This is tracked in this issue: https://github.com/commontk/CTK/issues/919

I'm closing this issue, please add any further comments related to this topic to https://github.com/commontk/CTK/issues/919. Thank you!
