### ISSUE TITLE
ctkBackTrace compilation warning

### ISSUE THREAD

**Issue by finetjul** [commontk/CTK#247]
C:\work\D\MSVTK\MSVTK-Superbuild-Debug-64bits-nightly-4.7.3-CMake 2.8.8\CTK\Libs\Core\ctkBackTrace.cpp(92): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data

**Comment by jcfr** [comment]
Closing. Most likely fixed by https://github.com/commontk/CTK/commit/d6c078190f8ec8bd68a7320e8b2d8eff5fa4964a
