### ISSUE TITLE
Qt5 compatibility

### ISSUE THREAD

**Issue by saschazelzer** [commontk/CTK#277]
This issue tracks the work on making CTK compatible with Qt5.

The main goals are:
- Enhance the build system to support both Qt4 and Qt5
- Use the modular structure of Qt5 and let CTK libraries state their Qt5 module dependencies explicitly

**Comment by jcfr** [comment]
Closing. Support for Qt5 has been integrated.

**Comment by lassoan** [comment]
We use CTK with VS2015 and Qt5 without problems. If you need help then you need to provide details about how you configure your build and what error you get exactly.
