### ISSUE TITLE
The value of "language" in slicer.ini  is incorrectly

### ISSUE THREAD

**Issue by iamzengwenye** [commontk/CTK#282]
In method  ctkLanguageComboBoxPrivate::languageItem in ctkLanguageComboBox.cpp
data = locale.name()  set the value of "language" in slicer.ini. This value come from one of the qm file names and determine  this qm file to be loaded.  So there is a contradiction here.

**Comment by jcfr** [comment]
Closing. The widget has been improved in the following pull-requests:
* https://github.com/commontk/CTK/pull/1019
* https://github.com/commontk/CTK/pull/1024
* https://github.com/commontk/CTK/pull/1028
