### ISSUE TITLE
Export mandatory Qt components 

### ISSUE THREAD

**Issue by finetjul** [commontk/CTK#301]
When building CTK, Qt components (QtCore QtGUI QtXml QtXML... ) are correctly configured.
However, when "using" CTK, including some files (e.g. ctkLayoutManager) require those components to be configured when Qt is configured.
A mechanism should be available for applications/libraries to know which Qt components are required when building CTK.
Maybe a call like the following one should be done in the CTKConfig.cmake or UseCTK.cmake:

```
find_package( Qt4 COMPONENTS QtCore QtGUI QtXML ...)
```

**Comment by jcfr** [comment]
Since this has been addressed for Qt5 in https://github.com/commontk/CTK/commit/448aaf3c3e0d53407b4ea000a947276bd3102817, I am closing.

Variable is named `CTK_QT5_COMPONENTS`
