### ISSUE TITLE
create alternative dicom browsing widgets

### ISSUE THREAD

**Issue by pieper** [commontk/CTK#330]
After discussion at ctk hackfest Canada, we decided to try breaking apart the current ctkDICOMModel class into a set of reusable components.

**Comment by jcfr** [comment]
@pieper @mehrtash @AndreasFetzer Can this issue be closed ?

**Comment by cpinter** [comment]
I guess so, but let's hear from those who were more involved in this than I

**Comment by AndreasFetzer** [comment]
Yes this issue can be closed. The new DICOM browsing widgets were integrated quiet a while ago.
