### ISSUE TITLE
Qt Designer crash when QSpinBox inside ctkCollapsible[GroupBox|Button] 

### ISSUE THREAD

**Issue by finetjul** [commontk/CTK#349]
In Qt Designer, dropping a spinbox inside a ctkCollapsibleGroupBox or ctkCollapsibleButton can lead to a crash.
Initially reported here: http://www.na-mic.org/Bug/view.php?id=2009

**Comment by jamesobutler** [comment]
For anyone that comes across this:

When using Qt4 Qt Designer, creating a QDoubleSpinBox or QSpinBox by dropping it inside a ctkCollapsibleGroupBox still causes Qt Designer to crash. Also [observed](https://github.com/commontk/CTK/commit/36f72607d964e8216ea967e7ae68af92fca00f1c#commitcomment-6549306) by another user. 

**Option1:** To avoid this you can create the QDoubleSpinBox or QSpinBox by dropping it outside of the ctkCollapsibleGroupBox and then dragging the spin box into the ctkCollapsibleGroupBox.
**Option2:** You can use a ctkDoubleSpinBox by dropping it directly inside a ctkCollapsibleGroupBox and that won't cause Qt Designer to crash.

**Option3:** Use Qt5 Qt Designer and you won't have these issues. (Tested using Qt. 5.10.1)
