### ISSUE TITLE
Console default prompt and cursor position issues

### ISSUE THREAD

**Issue by finetjul** [commontk/CTK#370]
Run ctkConsoleTest1 in interactive mode:
a) the prompt '$' is not displayed, only after Enter is typed

In the prompt line, type (Ctrl+Left arrow):
b) <s>the cursor is moved to the left of the prompt '$', it should be to the right</s>

Write multiple commands with Enter. 
Write a 2 line command, move cursor in the first line. And press the down key to move the cursor to the 2nd line
c) the line is erased (history is called). Multiple solution possible ( 1) might be enough):
    - 1) on down, don't call the history if there is no command in history (similar to shell console)
    - 2) don't call history if cursor can be moved
    - 3) don't call history if up/down key is pressed with modifier (shift, control...) 
Before recovering history, note that the current line should be added in history to be restored if needed (see shell console)

Go at the end of a prompt line. Hold SHIFT and press HOME
d) text is not selected. 

Related issues #294, #295

**Comment by jcfr** [comment]
Closing this issue. Despite of "the prompt '$' is not displayed, only after Enter is typed" , all issues are addressed in the current master.
