### ISSUE TITLE
ctkLanguageComboBoxTest fails - bad test name

### ISSUE THREAD

**Issue by pieper** [commontk/CTK#391]
Libs/Widgets/Testing/Cpp/ctkLanguageComboBoxTest.cpp

http://my.cdash.org/testDetails.php?test=12705674&build=537985

Test output
Available tests:
1. ctkActionsWidgetTest1
2. ctkAddRemoveComboBoxTest1
3. ctkAxesWidgetTest1
4. ctkButtonGroupTest1
5. ctkCheckBoxPixmapsTest1
6. ctkCheckBoxTest1
7. ctkCheckableComboBoxTest1
8. ctkCheckableHeaderViewTest1
9. ctkCheckableHeaderViewTest2
10. ctkCheckableModelHelperTest2
    1. ctkCheckablePushButtonTest1
    2. ctkCollapsibleButtonTest1
    3. ctkCollapsibleButtonTest2
    4. ctkCollapsibleGroupBoxTest1
    5. ctkColorDialogTest1
    6. ctkColorDialogTest2
    7. ctkColorPickerButtonTest1
    8. ctkComboBoxTest1
    9. ctkCompleterTest1
    10. ctkConsoleTest1
    11. ctkCoordinatesWidgetTest
    12. ctkCoordinatesWidgetTest1
    13. ctkCoordinatesWidgetValueProxyTest
    14. ctkCrosshairLabelTest1
    15. ctkDirectoryButtonTest1
    16. ctkDoubleRangeSliderTest
    17. ctkDoubleRangeSliderTest1
    18. ctkDoubleRangeSliderTest2
    19. ctkDoubleRangeSliderValueProxyTest
    20. ctkDoubleSliderTest
    21. ctkDoubleSliderTest1
    22. ctkDoubleSliderValueProxyTest
    23. ctkDoubleSpinBoxTest
    24. ctkDoubleSpinBoxTest1
    25. ctkDoubleSpinBoxValueProxyTest
    26. ctkDynamicSpacerTest1
    27. ctkDynamicSpacerTest2
    28. ctkErrorLogWidgetTest1
    29. ctkExpandButtonTest1
    30. ctkExpandableWidgetTest1
    31. ctkFileDialogTest1
    32. ctkFlatProxyModelTest
    33. ctkFittedTextBrowserTest1
    34. ctkFlowLayoutTest1
    35. ctkFontButtonTest
    36. ctkLayoutManagerTest1
    37. ctkMaterialPropertyPreviewLabelTest1
    38. ctkMaterialPropertyWidgetTest1
    39. ctkMaterialPropertyWidgetTest2
    40. ctkMatrixWidgetTest
    41. ctkMatrixWidgetTest1
    42. ctkMatrixWidgetTest2
    43. ctkMenuButtonTest1
    44. ctkMenuComboBoxTest1
    45. ctkMenuComboBoxTest2
    46. ctkMenuComboBoxTest3
    47. ctkMessageBoxDontShowAgainTest
    48. ctkModalityWidgetTest1
    49. ctkPathLineEditTest1
    50. ctkPathListWidgetTest
    51. ctkPathListWidgetWithButtonsTest
    52. ctkPopupWidgetTest1
    53. ctkProxyStyleTest1
    54. ctkRangeSliderTest
    55. ctkRangeSliderTest1
    56. ctkRangeWidgetTest
    57. ctkRangeWidgetTest1
    58. ctkRangeWidgetValueProxyTest
    59. ctkDateRangeWidgetTest1
    60. ctkScreenshotDialogTest1
    61. ctkSearchBoxTest1
    62. ctkSearchBoxTest2
    63. ctkSettingsPanelTest
    64. ctkSettingsPanelTest1
    65. ctkSettingsTest1
    66. ctkSettingsDialogTest1
    67. ctkSignalMapperTest1
    68. ctkSliderWidgetTest
    69. ctkSliderWidgetTest1
    70. ctkSliderWidgetTest2
    71. ctkSliderWidgetValueProxyTest
    72. ctkThumbnailListWidgetTest1
    73. ctkThumbnailLabelTest1
    74. ctkToolTipTrapperTest1
    75. ctkTreeComboBoxTest1
    76. ctkWidgetsUtilsTest1
    77. ctkWidgetsUtilsTestGrabWidget
    78. ctkWorkflowWidgetTest1
    79. ctkWorkflowWidgetTest2
    80. ctkExampleUseOfWorkflowWidgetUsingDerivedSteps
    81. ctkExampleUseOfWorkflowWidgetUsingSignalsAndSlots
    82. ctkCrosshairLabelTest2
        Failed: ctkLanguageComboBoxTest is an invalid test name.

**Comment by jcfr** [comment]
Closing. Superseded by https://github.com/commontk/CTK/issues/764
