### ISSUE TITLE
CMake warnings with CMake 2.8.12.1

### ISSUE THREAD

**Issue by cpinter** [commontk/CTK#426]
I get this warning when building a Slicer extension, and I get it many times (so it slows down the build process):

CMake Warning (dev) at C:/devel/Slicer4/CMake/SlicerMacroPythonWrapModuleVTKLibrary.cmake:97 (include):
  Syntax Warning in cmake code at
    C:/devel/Slicer4_D64-bin/CTK/CMake/ctkMacroCompilePythonScript.cmake:226:24
  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  SlicerRtCommon/CMakeLists.txt:54 (SlicerMacroPythonWrapModuleVTKLibrary)
This warning is for project developers.  Use -Wno-dev to suppress it.
CMake Warning (dev) at C:/devel/Slicer4/CMake/SlicerMacroPythonWrapModuleVTKLibrary.cmake:97 (include):
  Syntax Warning in cmake code at
    C:/devel/Slicer4_D64-bin/CTK/CMake/ctkMacroCompilePythonScript.cmake:226:29
  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  SlicerRtCommon/CMakeLists.txt:54 (SlicerMacroPythonWrapModuleVTKLibrary)
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by jcfr** [comment]
Fixed by 5dae408
