### ISSUE TITLE
build fails on mac 10.9.1 due to VTK and ITK versions of libtiff

### ISSUE THREAD

**Issue by pieper** [commontk/CTK#429]
I tried a fresh build of CTK on a freshly updated mac and got the link errors pasted below.

This seems to be the same issue reported here:

http://fink.9193.n7.nabble.com/Failed-phase-compiling-vtk510-5-10-1-1-failed-td44492.html

Issue also occurs with the default version of ITK.

Linking C shared library ../../bin/libvtktiff.dylib

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_close.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_codec.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_compress.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_dir.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_dirinfo.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_dirwrite.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_dirread.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_dumpmode.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_error.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_fax3.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_flush.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_getimage.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_jpeg.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___inline_isfinitef in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___inline_isfinited in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___inline_isfinitel in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___inline_isinff in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___inline_isinfd in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___inline_isinfl in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___inline_isnanf in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___inline_isnand in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___inline_isnanl in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___inline_signbitf in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___inline_signbitd in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___inline_signbitl in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___inline_isnormalf in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___inline_isnormald in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___inline_isnormall in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___sincosf in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___sincos in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___sincospif in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___sincospi in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_luv.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_lzw.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_next.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_ojpeg.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_open.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_packbits.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___inline_isfinitef in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___inline_isfinited in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___inline_isfinitel in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___inline_isinff in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___inline_isinfd in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___inline_isinfl in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___inline_isnanf in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___inline_isnand in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___inline_isnanl in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___inline_signbitf in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___inline_signbitd in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___inline_signbitl in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___inline_isnormalf in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___inline_isnormald in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___inline_isnormall in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___sincosf in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___sincos in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___sincospif in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___sincospi in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_pixarlog.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_predict.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_print.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_read.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_strip.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_swab.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_thunder.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_tile.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_version.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_warning.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_write.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_zip.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___inline_isfinitef in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___inline_isfinited in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___inline_isfinitel in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___inline_isinff in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___inline_isinfd in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___inline_isinfl in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___inline_isnanf in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___inline_isnand in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___inline_isnanl in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___inline_signbitf in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___inline_signbitd in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___inline_signbitl in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___inline_isnormalf in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___inline_isnormald in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___inline_isnormall in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___sincosf in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___sincos in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___sincospif in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___sincospi in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_color.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_extension.c.o

duplicate symbol ___sputc in:

    CMakeFiles/vtktiff.dir/tif_aux.c.o

    CMakeFiles/vtktiff.dir/tif_unix.c.o

ld: 91 duplicate symbols for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

make[2]: *** [bin/libvtktiff.5.10.1.dylib] Error 1

make[1]: *** [Utilities/vtktiff/CMakeFiles/vtktiff.dir/all] Error 2

make: *** [all] Error 2

**Comment by jcfr** [comment]
@pieper Please, if this is still a problem, consider re-opening this issue.
