### ISSUE TITLE
missing dcmtk log4cplus symbol on travis build

### ISSUE THREAD

**Issue by pieper** [commontk/CTK#488]
I've started playing with travis-ci.org (following up on the work @saschazelzer did at the Wash U hackfest).  I like travic-ci :+1: 

I've been able to get things running, and even have a dummy x server, all pretty easy:

https://github.com/pieper/CTK/compare/commontk:master...master

But a couple tests fail due to missing dcmtk symbols, and I think this is a legitimate bug in CTK:

http://my.cdash.org/testDetails.php?test=15588980&build=620826

http://my.cdash.org/testDetails.php?test=15588978&build=620826

Any suggestions @jcfr or @trabs ? 

Here is the build log:

https://travis-ci.org/pieper/CTK/builds/28169843

**Comment by jcfr** [comment]
Closing  this old issue. CI build are now done using CircleCI.
