### ISSUE TITLE
consider merging travis-ci into trunk

### ISSUE THREAD

**Issue by pieper** [commontk/CTK#489]
I think we should enable travis-ci for the CTK repository.

I have done it for my fork of CTK and it is slick.

https://github.com/pieper/CTK/compare/commontk:master...master

@saschazelzer I didn't find a branch in your github with a .travis.ym. but was able to copy some bits from your previous build.  Note that the Xdummy/xpra virtual X server seems to work correctly so I think this will be valuable for catching build issues.

**Comment by jcfr** [comment]
Since as of https://github.com/commontk/CTK/commit/1dc6c81ab6e5a26280645bd68afbca4c0e7426c7, we now have CircleCI running. I s suggest we close this issue.

@saschazelzer I also suggest we remove the older travic-ci topics ? What do you think.

**Comment by saschazelzer** [comment]
I am not familiar with CircleCI. If it can do what Travis CI can do, great.

Travis CI has support for OS X, which I didn't find on CircleCI yet, so we might want to keep this branch around for Mac OS testing (if someone wants to push that), even if it is without gui tests running.

**Comment by jcfr** [comment]
Good point. It makes sense to keep the topics then.

**Comment by jcfr** [comment]
Closing. Continuous integrate is now done using CircleCI.

If you would like to work further on the use of TravisCI, please create a new PR with the suggested improvements. 

Thanks
