### ISSUE TITLE
Search box clear icon quite harsh

### ISSUE THREAD

**Issue by cpinter** [commontk/CTK#501]
The big red 'X' button to clear a search field (CTK\Libs\Widgets\Resources\Icons\clear.svg) is very harsh. This kind of icon is mostly used to indicate a problem. In 3D Slicer for example (that uses CTK), the same icon appears in the bottom right corner to let the user know there is a new message in the error log.

Most applications that have similar search fields use a more subtle 'X' that does the very same thing, but doesn't alert the user. (Few examples: Windows Explorer, Skype, MS Outlook, Evernote).

I think a simple but noticeable gray 'X' would suffice.

**Comment by cpinter** [comment]
Julien, this is still an issue (at least the icon does not appear in the nightlies). Did you close it because you solved it somehow or because it is to be ignored?

**Comment by finetjul** [comment]
I closed it because I thought that it was fixed -> I can't reproduce the issue within CTK.
Sorry about that.

**Comment by cpinter** [comment]
No problem. Unfortunately although the icon is committed and everything seems fine, still the old icon shows up in Slicer. This may not be a CTK issue, but I wouldn't close this until resolved.
I'll investigate it again in the coming weeks. Thanks!

**Comment by cpinter** [comment]
THe icon now shows up correctly, closing the issue.
