### ISSUE TITLE
MacOS X 10.9 (Mavericks) : Help needed with the DICOM widgets

### ISSUE THREAD

**Issue by gianrig** [commontk/CTK#510]
For my company's needs i'm trying to compile and use CTK within Qt Creator. I've been successful in compiling Qt Creator 2.5.0 and CTK with Qt 4.8.2 using gcc 4.9 and Apple's Clang for the C++ part but i seem to be unable to get Qt Creator to load the DICOM widgets. I have followed and adapted the instructions on the project's page (i mean www.commontk.org. Btw, just a heads up, it's a bit outdated so i had to figure a few things out for myself. Could use a renewal) and played with the environment variables but to no avail. What else could i be missing ? Please get in touch with me at gianluca.rigon@growideas.eu

Thanks very much

```
                     Gianluca Rigon
```

**Comment by jcfr** [comment]
@gianrig Using Qt5 should definitively help. Let us know if you still have issue. In the mean time, I am closing this old issue.
