### ISSUE TITLE
Add compact and detailed mode to ctkDICOMTableView and ctkDICOMTableManager

### ISSUE THREAD

**Issue by rfloca** [commontk/CTK#518]
Introduce "compact and detailed view mode" to ctkDICOMTableView and ctkDICOMTableManager. Basic idea is that you can give the widgets a list of "high priority" tags.
In compact mode all columns of non priority tags will be filter.
In detailed mode everything is shown.
You can define the active mode via property / slot (to e.g. easily connect it with a control widget signal).

**Comment by jcfr** [comment]
@mehrtash  @fedorov @pieper @cpinter  Is this something on DICOM roadmap ?

**Comment by fedorov** [comment]
It's the first time I see this. I am not quite sure I understand this request.

**Comment by rfloca** [comment]
Yes, I worked on that topic while the last ctk hackfest. It is nearly finished (we had some glitsches with the correct column resizing when the compact view was activated).

The reason why it was not already pushed was the combination of pre-holiday-season-crunch-time and paternity leaf till last week.

If I know that someone else is interested in that issue, I will raise the priority on that and see that everything is cleaned up and pushed soon.

Best regards,
Ralf

________________________________
Von: Jean-Christophe Fillion-Robin [notifications@github.com]
Gesendet: Donnerstag, 5. Februar 2015 07:01
An: commontk/CTK
Cc: Floca, Ralf Omar
Betreff: Re: [CTK] Add compact and detailed mode to ctkDICOMTableView and ctkDICOMTableManager (#518)


@mehrtash<https://github.com/mehrtash> @fedorov<https://github.com/fedorov> @pieper<https://github.com/pieper> @cpinter<https://github.com/cpinter> Is this something on DICOM roadmap ?

�

**Comment by jcfr** [comment]
@rfloca Thanks for the comment. I was just doing some spring cleaning on the issue tracker and was wondering what was the status.

**Comment by jcfr** [comment]
Closing. Performance and usability of the DICOM browser have been improved in https://github.com/commontk/CTK/pull/886
