### ISSUE TITLE
no garbage supported 

### ISSUE THREAD

**Issue by towerbj** [commontk/CTK#534]

**Comment by jcfr** [comment]
Hi @towerbj , 

Thanks for using CTK. 

In order to better understand the problem, could you be a little bit more specific about the issue you are reporting ?

Thanks
Jc

**Comment by towerbj** [comment]
Environment: OSX10.10.2  XCODE 6.1

When I compiled the CTK project,  error information showed as follows:
"Garbage collection is no longer supported".
This error happens, when the scheme of "VTK" included in the CDK is compiled.
I have ever compiled the VTK project standalone, such error also happened, but I can correct it by modifying the CMakelist of the project:  removing the "-fobjc-gc" choice.
But I don't know how to deal with this problem here. As u know, I am a rookie for this.

**Comment by towerbj** [comment]
Hi,@jcfr:

Thanks for your response. I am not sure what kind of information you need? here is error building report as follows:
The following build commands failed:
           CompileC /Users/pliaobin/Documents/LiaoBin/CTK/CTK_MAC/VTK-build/Rendering/VTK.build/Debug/vtkRendering.build/Objects-normal/x86_64/vtkCocoaRenderWindow.o Rendering/vtkCocoaRenderWindow.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/pliaobin/Documents/LiaoBin/CTK/CTK_MAC/VTK-build/Rendering/VTK.build/Debug/vtkRendering.build/Objects-normal/x86_64/vtkCocoaGLView.o Rendering/vtkCocoaGLView.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/pliaobin/Documents/LiaoBin/CTK/CTK_MAC/VTK-build/Rendering/VTK.build/Debug/vtkRendering.build/Objects-normal/x86_64/vtkCocoaRenderWindowInteractor.o Rendering/vtkCocoaRenderWindowInteractor.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(3 failures)

and part of the sh script:
 -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks -fPIC -fobjc-gc -MMD -MT dependencies -MF /Users/pliaobin/Documents/LiaoBin/CTK/CTK_MAC/VTK-build/Rendering/VTK.build/Debug/vtkRendering.build/Objects-normal/x86_64/vtkCocoaRenderWindow.d --serialize-diagnostics /Users/pliaobin/Documents/LiaoBin/CTK/CTK_MAC/VTK-build/Rendering/VTK.build/Debug/vtkRendering.build/Objects-normal/x86_64/vtkCocoaRenderWindow.dia -c /Users/pliaobin/Documents/LiaoBin/CTK/CTK_MAC/VTK/Rendering/vtkCocoaRenderWindow.mm -o /Users/pliaobin/Documents/LiaoBin/CTK/CTK_MAC/VTK-build/Rendering/VTK.build/Debug/vtkRendering.build/Objects-normal/x86_64/vtkCocoaRenderWindow.o
error: garbage collection is no longer supported

**Comment by jcfr** [comment]
Fixed by 18fffba

Thanks for reporting the problem.

Note that the version of VTK currently checkout by CTK is the VTKv5, considering CTK also supports to be built against VTKv6 ... we should probably update the `CMakeExternals/VTK.cmake` file.

Considering that within [Slicer](http://github.com/Slicer/Slicer) (and most likely other project), CTK is configured with VTK build (or install tree) build outside of Slicer ... this explain why the file within CTK have not been updated.
