### ISSUE TITLE
Building problem with qt5-ctk

### ISSUE THREAD

**Issue by ricardosalinase** [commontk/CTK#547]
Hello,

I would like to build the qt5-ctk library with cmake using QT 5.4.0 with mingw32.
I changed the version in ctkMacroSetupQt.cmake to "5" with
set(CTK_QT_VERSION "5" CACHE STRING "Expected Qt version")
but I get the same Error Message when trying with 4 (which is also installed).
Do you have any idea what this could cause?

This is the output of cmake:

CMake Error at CMake/ctkMacroSetupQt.cmake:74 (message):
  error: Qt4 was not found on your system.  You probably need to set the
  QT_QMAKE_EXECUTABLE variable
Call Stack (most recent call first):
  CMakeLists.txt:398 (ctkMacroSetupQt)

-- Found unsuitable Qt version "5.4.0" from C:/Qt/5.4/mingw491_32/bin/qmake.exe
-- Configuring incomplete, errors occurred!
See also "C:/Users/rsalinas/Documents/Software/HelloCmake/CTK-qt5/CTK-superbuild/CMakeFiles/CMakeOutput.log".

Thanks a lot,
Ricardo Salinas

**Comment by finetjul** [comment]
Hi,
You are not supposed to edit the source files to configure CTK.
Just use CMake (gui or command line) and specify the value of the following variables:
 * CTK_QT_VERSION (to 5)
 * CMAKE_PREFIX_PATH (with the path to the cmake folder in Qt)

**Comment by ricardosalinase** [comment]
Thank you Man, now I can build the CommonCTK. but i have a problem when i build the ctkWidgets, so many errors appears like:

-'ctkCollapsibleButtonPrivate' was not declared in this scope
   QScopedPointer<ctkCollapsibleButtonPrivate> d_ptr;
- error: 'ctkCollapsibleButtonPrivate' does not name a type
   Q_DECLARE_PRIVATE(ctkCollapsibleButton);

In total 82 errors appear.

Do you have a suggestion for solving that errors, I think it could be that there is some configuration left in the cmakelist.txt but I have not found it yet.

**Comment by jcfr** [comment]
Hi, 

To summarize, doing the following fail:

* Start Git Bash
** `git clone git://github.com/commontk/CTK`
** mkdir CTK-build

* Start mingw terminal
* Run CMake-gui or cmake from the mingw terminal
** Add two entries: `CTK_QT_VERSION` and `CMAKE_PREFIX_PATH`
** Configure selecting the expected generator (mingw)

Could you also confirm that Qt5 is built using mingw32 ?

**Comment by ricardosalinase** [comment]
I am not following those steps, because I use Cmake in QT Creator. In Cmake-gui I miss libgcc_s_dw2-1.dll and I dont know how I can use the cmake in windows terminal.


So there are my steps for use the CTK in qt5.

1) Clone the CTK-QT5 repository 
* clone git://github.com/commontk/CTK/tree/qt5

I use the cmake(3.1.2) i included in qtcreator for build the CTK-qt5 project (qt 5.4.0)

2) Add two lines in cmakelists.txt of mainfolder of CTK-qt5:

*set(CTK_QT_VERSION 5)
*set(CMAKE_PREFIX_PATH MY_PATH_TO_CMAKE.EXE)

3)This step may be wrong because finetjul says it is not supposed to edit the source files to configure CTK : In cmake/ctkMacroSetupQT set(CTK_QT_VERSION "5" CACHE STRING "Expected Qt version") instead of "4".

if i don't change that i have the following error:

CMake Error at CMake/ctkMacroSetupQt.cmake:75 (message):
  error: Qt4 was not found on your system.  You probably need to set the
  QT_QMAKE_EXECUTABLE variable
Call Stack (most recent call first):
  CMakeLists.txt:399 (ctkMacroSetupQt).


5) When i build CTK-Superbuild i get some error /D: no such file or directory,
i read the output compile and i get this:
g++.exe: error: /D: No such file or directory
g++.exe: error: _CRT_SECURE_NO_WARNINGS: No such file or directory
Libs\Core\Testing\Cpp\CMakeFiles\CTKDummyPlugin.dir\build.make:59: recipe for target 'Libs/Core/Testing/Cpp/CMakeFiles/CTKDummyPlugin.dir/ctkDummyPlugin.cpp.obj' failed

So, i go to CTK-qt5\Libs\Core\Testing\Cpp\cmakelist.txt and change the add_definition argument:
if(WIN32)
  add_definitions( -D _CRT_SECURE_NO_WARNINGS)
endif()

Now i can compile the core of CTK.

6) i configure cmakelists.txt in / to build the widgets library:

ctk_lib_option(Widgets
               "Build the Widgets library" ON
               CTK_ENABLE_Widgets OR (CTK_ENABLE_DICOMApplicationHosting AND CTK_BUILD_EXAMPLES) OR CTK_USE_QTTESTING)

ctk_enable_option(Widgets "Enable Qt Widget libraries" ON
                  CTK_LIB_Widgets)
			   

7) Build again, and get the CTKWidgets Librarys.

8) CLone the example https://github.com/commontk/Examples

9) Modify some lines in cmakelist.txt inside the example 

find_package(QT5 REQUIRED) //instead of Qt4

//Qt5 packages required
find_package(QT5Widgets REQUIRED)
find_package(QT5Xml REQUIRED)
find_package(QT5OpenGL REQUIRED)

target_link_libraries(example1 CTKWidgets Qt5::Widgets Qt5::Xml Qt5::OpenGL) 
qt5_use_modules(example1 Widgets Xml OpenGL) 

The include libraries can be found in the code, but when i run the project nothing appears and its crashes

What could be the error of my procedure?

**Comment by jcfr** [comment]
* The master of CTK has support for qt5, there is no need to checkout the `qt5` branch. This branch should be removed (See #557)

* Would be great if you could submit a pull request to update the `commontk/Examples` sources to support either Qt4 or Qt5.

* The error related to `add_definitions( -D _CRT_SECURE_NO_WARNINGS)` happens because this definition should be added only for `Microsoft compiler` and not for `MinGW`

**Comment by jcfr** [comment]
xref #644

**Comment by KangolHsu** [comment]
maybe need restar computer. @finetjul

**Comment by jcfr** [comment]
> maybe need restar computer

I am not sure restarting the computer will help.

Instead, I would recommend to build this topic: https://github.com/commontk/CTK/tree/improve-qt-5-support

**Comment by jcfr** [comment]
Qt5 support has been integrated into master. If there is still issue building against Qt5, consider creating a new issue. Thanks
