### ISSUE TITLE
Qt5 build produces linker errors on all platforms

### ISSUE THREAD

**Issue by AndreasFetzer** [commontk/CTK#575]
The "default" build, i.e. without activating any specific module works fine.
But if you activate e.g. CTK_ENABLE_DICOM or CTK_LIB_XNAT/Core you will end up with the following CMake warnings:

```
CMake Warning (dev) at CMake/ctkMacroBuildLib.cmake:152 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "CTKXNATCore" links to target "Qt5::Gui" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  Libs/XNAT/Core/CMakeLists.txt:60 (ctkMacroBuildLib)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

And then the build fails (in case of xnat core) with the following message:

```
Linking CXX shared library ../../../bin/libCTKXNATCore.dylib
ld: library not found for -lQt5::Gui
```

However if you additionally activate CTK_LIB_Widgets everything works fine.

**Comment by jcfr** [comment]
Does it help to add line like these ones: https://github.com/commontk/CTK/blob/007ecceaa8e78d688dfd4a55cb3ad57f8700a1b9/Libs/Widgets/CMakeLists.txt#L354-L356 ?

**Comment by AndreasFetzer** [comment]
I added

`if(CTK_QT_VERSION VERSION_GREATER "4")`
`   list(APPEND KIT_target_libraries Qt5::Gui)`
`endif()`

to Libs/Xnat/Core/CMakeLists.txt but I still get the above mentioned linker error

**Comment by jcfr** [comment]
Closing. The Qt5 support recently went through a lot of improvement.

If this is still a problem, please create a new issue.

Thanks
