### ISSUE TITLE
splash handler bug

### ISSUE THREAD

**Issue by espakm** [commontk/CTK#602]
I noticed a bug when browsing the code.

https://github.com/commontk/CTK/blob/master/Libs/PluginFramework/ctkPluginFrameworkLauncher.cpp#L424

The endSplashHandler data member exists indeed, but it is never assigned. I think, it should be removed and the parameter should be used, instead.

**Comment by jcfr** [comment]
cc: @saschazelzer

**Comment by arcadien** [comment]
Hello,
I initiated a small fix for this one, to allow a clean splashscreen feature in Mitk.

https://github.com/commontk/CTK/pull/637

Regards,

**Comment by saschazelzer** [comment]
Fixed with PR #637 .
