### ISSUE TITLE
ctkDirectoryButton is hardly usable due to its fixed width

### ISSUE THREAD

**Issue by fedorov** [commontk/CTK#619]
This widget (http://www.commontk.org/docs/html/classctkDirectoryButton.html) is very inconvenient due to its fixed width constraint. Any plans to fix this?

Related long-standing issue in Slicer: http://www.na-mic.org/Bug/view.php?id=1672

Illustrative examples (width of the screenshot is the full width of retina display on a 15-inch mac):

![image](https://cloud.githubusercontent.com/assets/313942/11882175/0ac72b98-a4d9-11e5-82e6-d9147f5b9c23.png)

![image](https://cloud.githubusercontent.com/assets/313942/11882181/11e0121e-a4d9-11e5-8e03-eb1ef7aa0760.png)

**Comment by jcfr** [comment]
Closing. Fixed in https://github.com/commontk/CTK/pull/1016
