### ISSUE TITLE
The 'pointfile' element is not part of the execution model XSD yet

### ISSUE THREAD

**Issue by hmeine** [commontk/CTK#622]
I think @naucoin has introduced support for `<pointfile>` parameters, but `Libs/CommandLineModules/Core/Resources/ctkCmdLineModule.xsd` has not been updated yet.
As far as I know, that is the most official "spec" of CLIs' XML.

**Comment by naucoin** [comment]
Looking at the .xsd file, the pointfile needs to have a type that's a combo of fileType and pointType (for the coordinate system). I think I can make a new type that extends the fileType, calling it pointFileType.

**Comment by naucoin** [comment]
@hmeine Take a look at this change and let me know if it works for you (I used an online validator). If so I can do a pull request:
https://github.com/naucoin/CTK/commit/b8ee29ff949ea5314c3417584e653153182a9f62

Topic branch:
https://github.com/naucoin/CTK/tree/622-add-pointfile-element-to-execution-model-xsd

**Comment by hmeine** [comment]
To be honest, I have no good knowledge of XSD, but your addition looks totally sensible and is definitely useful as-is, if only for human understanding. :-)

**Comment by naucoin** [comment]
I was figuring it out as I went - I'll do the pull request to get some expert feedback!

**Comment by jcfr** [comment]
After confirming that existing CTKCLI tests are passing and fixing typy in commit message. LGTM

Cc: @saschazelzer

**Comment by naucoin** [comment]
I ran 8 tests found via
ctest -R CmdLine
and all passed. Were those the tests that you meant?

**Comment by jcfr** [comment]
@naucoin Indeed, these tests are expected to make use of the xsd schema.

**Comment by saschazelzer** [comment]
The xsd changes look good to me. At least they do not invalidate current xml files. The tests will at most (I don't remember the details) verify that the xml files used within the tests still validate against the new schema.

If CTK itself is to support the new parameter type, it would need to be added to https://github.com/commontk/CTK/blob/master/Libs/CommandLineModules/Frontend/QtGui/Resources/ctkCmdLineModuleXmlToQtUi.xsl such that it is generated in the GUI. The change would be analogous to the `file` and `geometry` parameters.

**Comment by hmeine** [comment]
Oh, I just thought it was already supported in the CTK GUI generation.  Maybe not, but that should be filed as a separate issue, I believe.

**Comment by hmeine** [comment]
OK, who will merge this? @naucoin ? @jcfr ?

**Comment by jcfr** [comment]
Integrated in 89639ec120b6dfc8

**Comment by naucoin** [comment]
@hmeine  New issue created: https://github.com/commontk/CTK/issues/626
