### ISSUE TITLE
One cannot know beforehand which CLIs support progress output

### ISSUE THREAD

**Issue by hmeine** [commontk/CTK#624]
Some CLIs support a progress bar, which I would like to support in MeVisLab as well.  However, I would like to only display a progress bar if the CLI outputs progress on stdout, which I cannot know before actually running.

I suggest to add an element (or attribute) to the allowed `--xml` output (and to `Libs/CommandLineModules/Core/Resources/ctkCmdLineModule.xsd`) in order to solve this issue.

**Comment by pieper** [comment]
Wouldn't it make sense for the progress bar to be hidden by default and
then shown only when a first progress event arrives?  This would avoid
requiring a flag which could be out of sync with the actual behavior of the
module (e.g. the default flag may be off, meaning that a developer would
need to know to turn it on before their progress outputs would be
displayed).

**Comment by hmeine** [comment]
I considered that, but in general, it is quite ugly to let user interface elements appear or vanish suddenly.
One could still do that if the flag is out of sync, but it would be definitely preferable to reserve space for the progress  bar if possible.

**Comment by pieper** [comment]
I agree that disappearing would be ugly, but in this case it's just an
element appearing, which is pretty normal and I still prefer we don't add
the flag.  Besides, there may be some cases where the CLI generates
progress and other cases where it doesn't so the semantics of this aren't
clear to me.

**Comment by hmeine** [comment]
The semantics would be "this CLI may output progress eventually [so do reserve GUI space for it]", and it would not hurt much if the flag is not set, bug progress output is sent.

"just an element appearing" however means that a relayouting is necessary.  First, it may happen that other GUI elements are shifted by this (think of a vertically layouted toolbox), which may lead to the user clicking on an element he/she did not intend to.  Second, remember that in MeVisLab the "panel" (toolbox) often is a separate window, which will then be resized, involving window management.  (For instance, under Linux the window manager may have placed the newly opened window at the screen's bottom, and when it gets enlarged, the new part will not be visible.)

I still believe there are good reasons not to "just let elements appear".

**Comment by hmeine** [comment]
Think of it like the width=/height= attributes of an img element in HTML.  Yes, they're optional, but in practice, they're crucial for a good user experience.

**Comment by saschazelzer** [comment]
One solution which I tried in CTK once was to always show the progress bar (empty at start) and after a CLI module is started, set it to "progress unknown" (which usually results in some animation of the progress bar with most UI toolkits). When the frontend receives a first real progress value, that value is set.

**Comment by pieper** [comment]
I like Sascha's idea.  Also I guess as an optional hint I don't mind the
progress bar flag.  As long as it's possible for the CLI to display
progress even if it's a legacy CLI that didn't have the flag set.

**Comment by hmeine** [comment]
@saschazelzer Isn't that also exactly what happens in Slicer?  However, I would prefer not to clutter all CLI module panels in MeVisLab with a progress bar by default.  The way the parameter panels work is just different compared to MeVisLab; for instance, they're not hidden automatically when you use another module.

**Comment by saschazelzer** [comment]
I do not remember how Slicer behaves with respect to CLI progress bars.

The additional flag can at most be viewed as a hint in my opinion. It can get out of sync with the actual implementation and there are also legacy CLIs around as Steve mentioned. I feel reluctant to add a flag which one cannot rely on. The UI issues make sense to me, but if you are concerned about limited available screen size, wouldn't a totally different progress monitoring approach be more suitable, instead of the bulky bar?

**Comment by hmeine** [comment]
OK, I will close this issue for now.  Too much pushback. ;-)
