### ISSUE TITLE
Qt 5.5 error: could not find git for clone of CTKData

### ISSUE THREAD

**Issue by dongtongtong** [commontk/CTK#628]
when I build CTK project, the following error occurred.

Make Error at D:/Program Files (x86)/CMake/share/cmake-3.4/Modules/ExternalProject.cmake:1737 (message):
  error: could not find git for clone of CTKData
Call Stack (most recent call first):
  D:/Program Files (x86)/CMake/share/cmake-3.4/Modules/ExternalProject.cmake:2430 (_ep_add_download_command)
  CMakeExternals/CTKData.cmake:43 (ExternalProject_Add)
  CMake/ctkMacroCheckExternalProjectDependency.cmake:568 (include)
  CMake/ctkMacroCheckExternalProjectDependency.cmake:614 (ExternalProject_Include_Dependencies)
  CMake/ctkBlockCheckDependencies.cmake:132 (ExternalProject_Include_Dependencies)
  CMakeLists.txt:974 (include)

**Comment by jcfr** [comment]
Thanks for your report.

> error: could not find git for clone of CTKData

Could you confirm you installed git and that the variable `GIT_EXECUTABLE` is properly set if you open the file `D:/path/to/CTK-build/CMakeCache.txt` ?

Hth
Jc

**Comment by dongtongtong** [comment]
Thank you for helping me .
