### ISSUE TITLE
CTK XNAT build fails due to wrong qRestAPI version

### ISSUE THREAD

**Issue by AndreasFetzer** [commontk/CTK#632]
If you activate the ctk xnat tree browser you will get the following build error:

`error:` no member named 'setHttpNetworkProxy' in 'ctkXnatAPI'
`d->xnat->setHttpNetworkProxy(proxy);`

**Comment by jcfr** [comment]
Fixed in https://github.com/commontk/CTK/commit/8403df53a7004a88a2bc8e9b55109c88f1516839

@AndreasFetzer Thanks for the PR :+1:
