### ISSUE TITLE
building CTKVisualizationVTKWidgetsPlugins error

### ISSUE THREAD

**Issue by howard-scu** [commontk/CTK#638]
I have no error while building CTK_LIB_Visualization/VTK/Widgets and CTK_LIB_Visualization/VTK/Core

but have the following errors while building CTK_LIB_Visualization/VTK/Widgets_USE_TRANSFER_FUNCTION_CHARTS

I dont know where is my problem

> 2>------ 已启动生成: 项目: CTKVisualizationVTKWidgetsPlugins, 配置: Debug Win32 ------
> 2>生成启动时间为 2016/4/6 16:18:53。
> 2>InitializeBuildStatus:
> 2>  正在对“CTKVisualizationVTKWidgetsPlugins.dir\Debug\CTKVisualizationVTKWidgetsPlugins.unsuccessfulbuild”执行 Touch 任务。
> 2>CustomBuild:
> 2>  所有输出均为最新。
> 2>ClCompile:
> 2>  所有输出均为最新。
> 2>ManifestResourceCompile:
> 2>  所有输出均为最新。
> 2>Link:
> 2>     正在创建库 C:/Users/Administrator/CTK/build1/bin/Debug/CTKVisualizationVTKWidgetsPlugins.lib 和对象 C:/Users/Administrator/CTK/build1/bin/Debug/CTKVisualizationVTKWidgetsPlugins.exp
> 2>ctkVTKVolumePropertyWidgetPlugin.obj : error LNK2019: 无法解析的外部符号 "public: __thiscall ctkVTKVolumePropertyWidget::ctkVTKVolumePropertyWidget(class QWidget *)" (??0ctkVTKVolumePropertyWidget@@QAE@PAVQWidget@@@Z)，该符号在函数 "public: virtual class QWidget \* __thiscall ctkVTKVolumePropertyWidgetPlugin::createWidget(class QWidget *)" (?createWidget@ctkVTKVolumePropertyWidgetPlugin@@UAEPAVQWidget@@PAV2@@Z) 中被引用
> 2>C:\Users\Administrator\CTK\build1\bin\designer\Debug\CTKVisualizationVTKWidgetsPlugins.dll : fatal error LNK1120: 1 个无法解析的外部命令

**Comment by jcfr** [comment]
Thanks for the report.

Which version of VTK are your building against ?

**Comment by howard-scu** [comment]
qt 4.8, vtk 5.10

**Comment by jcfr** [comment]
I suggest to suggest a recent version of VTK.

If you still have issue, please consider creating a new issue.

In the time, we are closing this issue.
