### ISSUE TITLE
QT5_CREATE_MOC_COMMAND has an additional parameter in Qt-5.6

### ISSUE THREAD

**Issue by jeromevelut** [commontk/CTK#641]
Qt/5.6/.../lib/cmake/Qt5Core/Qt5CoreMacros.cmake adds an additional "moc_depends" parameter which triggers an error during CTK/Libs/Widgets cmake processing.
Adding an empty string in QT5_CREATE_MOC_COMMAND, ctkMacroGenerateMocs.cmake, l29, solves the problem.

However, it's almost certain that it is not backward compatible with Qt-5.5.

**Comment by jcfr** [comment]
Thanks for the report

Fixed in 9440d3c9
