### ISSUE TITLE
 Link to "Experimental Qt5 support" broken

### ISSUE THREAD

**Issue by ruudsieb** [commontk/CTK#644]
The link on http://commontk.org/index.php/Build_Instructions to Experimental Qt5 support is broken, results in Not found.

Maybe update the build instructions page altogether?

**Comment by jcfr** [comment]
@ruudsieb Thanks for the note :+1: 

Qt5 support has been integrated into master. Using that `qt5` branch is not needed anymore.

I just updated the wiki accordingly.

**Comment by jcfr** [comment]
Thanks again for reporting the issue in the documentation. Do not hesitate to create additional issue if you encounter other discrepancies.
