### ISSUE TITLE
Update minimal version of DCMTK

### ISSUE THREAD

**Issue by nolden** [commontk/CTK#648]
Currently the superbuild default uses the last stable version of DCMTK. Rationale for this was the requirement or at least  idea to be able to build packages for debian while also includes this version. Recently debian has moved to a more recent snapshot of DCMTK and projects like MITK and Slicer which use CTK already provide newer DCMTK versions to the CTK build.

I suggest to update the superbuild default as well as the minimal supported version of DCMTK to DCMTK-3.6.1_20150924 which will allow us to remove also some C++ and CMake code that was necessary to support older versions.

**Comment by pieper** [comment]
+1

**Comment by jcfr** [comment]
Thanks @nolden
