### ISSUE TITLE
Enable testing using CircleCi

### ISSUE THREAD

**Issue by jcfr** [commontk/CTK#660]
Some time ago, @saschazelzer worked on setting up continuous integration using travis-ci. See [here](https://github.com/commontk/CTK/issues/489)

Since CTK tests requires a display, it was not straightforward and never made it to master.

To move forward with the testing, the idea would be to leverage the work of @thewtex related to [docker-opengl](https://github.com/thewtex/docker-opengl)

Here are possible steps:
* [x] Create a Dockerfile based on `thewtex/opengl` (see [here](https://github.com/thewtex/SlicerDocker/pull/5/commits/20a6c119de8e97605b84457a9ceea9569e196955) for an example)
* [x] Create a PR adding circle.yml file

cc: @lucasgandel @MayeulChassagnard @thewtex

**Comment by thewtex** [comment]
@jcfr Could the CircleCI service please be enabled on commontk/CTK?

**Comment by jcfr** [comment]
Lucas and you are both owner of the commontk org on docker. I will look
into adding you to the GitHub one asap

**Comment by jcfr** [comment]
Just added you to the CTK admin

**Comment by MayeulChassagnard** [comment]
Docker is fine, but we need to tell CircleCI to watch the GitHub repo. This
can only be done by the GitHub CTK owner.
Please login to CircleCI and go to the "Add Project" tab, then choose
"Follow project" for commontk/CTK.

Thanks,
Lucas and Mayeul

**Comment by thewtex** [comment]
Cool. The CircleCI service has now been enabled on commontk/CTK:

  https://circleci.com/gh/commontk/CTK/1

**Comment by jcfr** [comment]
Thanks @MayeulChassagnard, @LucasGandel and @thewtex for your help working on this.

Closing. Fixed in https://github.com/commontk/CTK/commit/1dc6c81ab6e5a26280645bd68afbca4c0e7426c7
