### ISSUE TITLE
Porting some of this to golang

### ISSUE THREAD

**Issue by joeblew99** [commontk/CTK#684]
I am working on a project for medical imaging using QT with some doctors in Berlin.

The framework uses qT 5.7 with golang. It's much easier for developers to work with I find than c++. 
Therecipe/Qt repo on github.

I want to port over the client side code in this report.
I just wanted Ted to let the team know as some people may be interested in this.

**Comment by jcfr** [comment]
@joeblew99 Did you make any progress porting the project to golang ?

We would be happy to link your project from the commontk wiki or even publish a blog (e.g on http://blog.kitware.com/)

In the mean time, I am closing this issue.

**Comment by joeblew99** [comment]
i made a fair bit on progress on DICOM aspects and a 3D webGL framework for tomography.
Next step will be getting pub / sub working with the 3D system to allow it to be parametric.

I am working on cloud based stuff the next 3 months though on another site so its going to be a long sloggggg....
