### ISSUE TITLE
extra blank line when printing values 

### ISSUE THREAD

**Issue by pieper** [commontk/CTK#731]
Probably due to https://github.com/commontk/CTK/commit/3d30e4d1608d18e734925441702bc64084d85f8d

As noticed here https://github.com/QIICR/QuantitativeReporting/issues/170#issuecomment-317481664, 

With a nightly build from a few days ago I get this:

<pre>
>>> i = '1.3.6.1.4.1.32722.99.99.267143140824284582760185651535851323805'
>>> s = "0010,0040"
>>> slicer.dicomDatabase.instanceValue(i,s)
u'M'
</pre>

But with my local build I get this (extra newline before the value)
<pre>
>>> s = "0010,0040"
>>> i = '1.3.6.1.4.1.32722.99.99.267143140824284582760185651535851323805'
>>> slicer.dicomDatabase.instanceValue(i,s)

u'M'
</pre>

**Comment by pieper** [comment]
FYI @MayeulChassagnard @jcfr

**Comment by jcfr** [comment]
@MayeulChassagnard finished his internship few weeks ago. I will have a look.

**Comment by lassoan** [comment]
By the way, @MayeulChassagnard did an awesome job with the Python interactor. Fixing the annoying auto-complete bugs and being able to calling auto-complete without instantiating an object were great improvements.
