### ISSUE TITLE
When i move my app to other dir, the app doesn't work...

### ISSUE THREAD

**Issue by ysx1993** [commontk/CTK#781]
For example, my app is in `c:/app/` and i run it, it will generate the `plugins.db` which in `c:/app/configuration`, i know the `plugins.db` records the plug-in's meta information and the plug-in path. But when i move `c:/app/` to `d:/app`, it doesn't work... But after i delete `d:/app/configuration`, my app can work again.

So my guess is that the plug-in path in plugin.db causes the program to fail to start. Using `FRAMEWORK_STORAGE_CLEAN_ONFIRSTINIT` can solve my problem but I used `ctkManagedService` to save my plug-in information and `FRAMEWORK_STORAGE_CLEAN_ONFIRSTINIT` would delete my plug-in information when the program started, so it was not appropriate. 

Could you please give me some advice to solve this problem? Thank you!

**Comment by jcfr** [comment]
Hi @ysx1993 , 

I suspect the path written in `plugins.db` are absolute.

I suggest to look at the following code: https://github.com/commontk/CTK/blob/cdb75ce742f618112b8a0f299a484d00baa4e8ff/Libs/PluginFramework/ctkPluginStorageSQL.cpp#L412-L492

**Comment by ysx1993** [comment]
Hi @jcfr,
I know what you mean, thank you !

**Comment by jcfr** [comment]
> I know what you mean, thank you !

Does it mean that (1) we can close the issue for now and (2) you are looking into either improving CTK or updating the SQL lite database directly ?

**Comment by jcfr** [comment]
@ysx1993 If you have a chance, do not hesitate to propose a PR to accommodate your use case, in the mean time we are closing this issue.

**Comment by ysx1993** [comment]
@jcfr Thanks to you! I have fixed this bug by using relative path...
`QString pluginPath = QLatin1String("plugins");
ctkPluginFrameworkLauncher::addSearchPath(pluginPath, true);`
