### ISSUE TITLE
ctk\libs\visualization\vtk\core\vtkDiscretizableColorTransferChart.h(77): error C3646: “VTK_OVERRIDE”: 

### ISSUE THREAD

**Issue by c1a1o1** [commontk/CTK#790]
ctk\libs\visualization\vtk\core\vtkDiscretizableColorTransferChart.h(77): error C3646: “VTK_OVERRIDE”:

**Comment by jcfr** [comment]
Thanks for reporting the problem and our apology for the later reply.

To better understand the problem and hopefully fix it, could you create an other issue specifying:
* the build option used
* version of Qt

In the mean time, we are closing this issue.
