### ISSUE TITLE
incorrect behavior of changed settings indicator in settings dialog

### ISSUE THREAD

**Issue by jamesobutler** [commontk/CTK#799]
When a setting is changed in a ctkSettingsPanel an indicator is shown next to the panel title in the ctkSettingsDialog.  However, if the setting is registered with the OptionNone SettingOption and it gets changed, the setting key doesn't get removed from changed settings after applying settings or the indicator just doesn't update correctly.  The updated setting does correctly propagate to the associated QSettings ini file after applying settings.  If you display the ctkSettingsDialog again after applying settings, you have to toggle the same setting to get the changed settings indicator to update correctly.

It looks like this behavior has been present in CTK for awhile now, but I'm assuming the current behavior is incorrect.

Unfortunately, I don't have the c++ experience to debug/issue a fix.  Hopefully I've provided enough information to help point to a quick fix!

**Comment by pieper** [comment]
Thanks for the report - as you saw, nobody's worked on this code for a while so it's not clear if/when someone will fix this issue.  This would be a good topic as a learning experience for a new contributor.
