### ISSUE TITLE
Replace deprecated qt5_use_modules with target_link_libraries

### ISSUE THREAD

**Issue by emmenlau** [commontk/CTK#803]
In Qt 5.11, `qt5_use_modules` is removed. It has been marked as deprecated since a while, so there is probably no way back. The replacement is to use `target_link_libraries`. Currently, CTK fails to build with Qt 5.11 with error:
```
CMake Error at Libs/Core/Testing/Cpp/CMakeLists.txt:124 (qt5_use_modules):
  Unknown CMake command "qt5_use_modules".
```

**Comment by jcfr** [comment]
Thanks for reporting the problem. As soon as the associated PR is integrated, it should be fixed.
