### ISSUE TITLE
QSqlDatabasePrivate::database: requested database does not belong to the calling thread.

### ISSUE THREAD

**Issue by cnd** [commontk/CTK#814]
with qt 5.11 framework crashes on 

```
void ctkPluginStorageSQL::close()
{
  if (m_isDatabaseOpen)
  {
    QSqlDatabase database = QSqlDatabase::database(m_connectionName, false);
```

and really `::open()` was called from main thread but `::close()` is called from another one

**Comment by kislinsk** [comment]
This is currently a blocker for MITK as we need at least Qt 5.10.1 to get the WebEngine stuff right but unfortunately there's a bug in Qt 5.10 that makes it impossible to deploy a WebEngine enabled Qt application on Linux. So, last option is to use Qt 5.11.1 but now we have the crash mentioned in this issue when closing our application.

I try to have a look at it with the comment of @saschazelzer in #815 in mind.

**Comment by kislinsk** [comment]
I came up with a solution based on thread-local database connection pooling in ctkPluginStorageSQL. I'll create a pull request.

**Comment by kislinsk** [comment]
See pull request #818.

**Comment by jcfr** [comment]
Closing. This is fixed in https://github.com/commontk/CTK/commit/f500513709245b699891df95c5febd462236b35e
