### ISSUE TITLE
“ctkCompilerDetections_p.h”: No such file or directory

### ISSUE THREAD

**Issue by shouganhao** [commontk/CTK#867]
“ctkCompilerDetections_p.h”: No such file or directory when build CTK

**Comment by JoyPoint** [comment]
You can copy the file from ..\CTK\Libs\Core\ctkCompilerDetections_p.h 
to ..\CTK-build\CTK-build\Libs\PluginFramework\,
and rebuild.

**Comment by jcfr** [comment]
CTK is built daily without issue. Could you share how you configure and build CTK ? May be the build system should be improved to consider your use case.

**Comment by zhaosky** [comment]
I have the same question too.

**Comment by lassoan** [comment]
Could you share how you configure and build CTK ? May be the build system should be improved to consider your use case.

**Comment by zhaosky** [comment]
> Could you share how you configure and build CTK ? May be the build system should be improved to consider your use case.

Because of it tips me that file can't create directory in "c:",so I changed SuperBuild.cmake file,like that:
```
#add install command
if(WIN32)
	set(_INSTALL_CMD mingw32-make install)
else()
	set(_INSTALL_CMD make install)
endif()
#set install location
set(_INSTALL_DIR ${CTK_BINARY_DIR}/../CTKInstall)
```
and changed install path:
 -DCMAKE_INSTALL_PREFIX:PATH=${_INSTALL_DIR}

**Comment by zhaosky** [comment]
> Could you share how you configure and build CTK ? May be the build system should be improved to consider your use case.

I manually copyed the prompted file from“CTK-master\Libs\Core\ ” to the "build-CTK-master-CMake-Debug\CTK-build\Libs\PluginFramework\ " ,and continue to build the project. the problem was solved.

**Comment by jcfr** [comment]
It looks like you are using mingw, could you provide here the complete set of command user to configure and build CTK. For example:

```
git clone https://github.com/commontk/CTK
mkdir CTK-build
cd CTK-build
cmake -G "Name of the generator" ....
```

Few remarks:
* If you would like to install CTK, there is no need to modify the SuperBuild.cmake file, instead I suggest you build the `install` target from within the inner build directory.
* if it is really needed, there is no need to hardcode `mingw32-make`, instead the variable `${CMAKE_MAKE_PROGRAM}` should be used

**Comment by zhaosky** [comment]
Thanks for your help，I will try your propose.

**Comment by jcfr** [comment]
Closing this issue. 

Please, create a new issue if you still have problem.
