### ISSUE TITLE
error: type 'QString' does not provide a call operator

### ISSUE THREAD

**Issue by simohauml** [commontk/CTK#925]
I was trying to build CTK on Mac OS, with CTK_ENABLE_PluginFramework enabled.

Then I got error: 
`-- Build files have been written to: /Users/zhangyue/Libs/CTK-superbuild/CTK-build`
`[ 58%] Performing build step for 'CTK'`
`[ 17%] Built target CTKCore`
`[ 18%] Built target CTKDummyPlugin`
`[ 31%] Built target CTKCoreCppTests`
`[ 32%] Built target Snippet-CommandLineParser`
`[ 32%] Building CXX object Libs/PluginFramework/CMakeFiles/CTKPluginFramework.dir/ctkLDAPExpr.cpp.o`
`/Users/xxx/Libs/CTK/Libs/PluginFramework/ctkLDAPExpr.cpp:623:12:  error: type 'QString' does not provide a call operator`
`return QString()( );`

OS: Mac OS 10.15
XCode: 11.6
QT: Qt 5.15
CMake: 3.16.3

**Comment by lassoan** [comment]
This looks like a typo in a very recent commit - just replace this line:

    return QString()( );

by

    return QString();

From Qt changes-5.9.0 document:

> QString::null is now deprecated. When used to construct a QString, use
     QString() instead. When used to compare to a QString, replace with
     QString::isNull().

@jamesobutler

**Comment by jcfr** [comment]
See https://github.com/commontk/CTK/commit/ac7ef86c7023c899b9d57297f91aa540881797a2

![image](https://user-images.githubusercontent.com/219043/92197078-bfb64d00-ee3e-11ea-9560-9036ba4a6754.png)

**Comment by jamesobutler** [comment]
Weird. Yeah not sure what was up with that one instance.
