### ISSUE TITLE
Build error LNK2019 about QLinkedListData

### ISSUE THREAD

**Issue by renyuhuiharrison** [commontk/CTK#929]
In cmake-gui, I check the  PluginFramework option. I configure and generate CTK.sln with cmake successfully. The solution happens to have a compile error (the following code is partial and the full output text is in the attachment):

`4>ctkSettings.cpp
20>   Creating library E:/CodeProjects/CTK/CTK-git/CTK_build/bin/Debug/org_commontk_plugingenerator_core.lib and object E:/CodeProjects/CTK/CTK-git/CTK_build/bin/Debug/org_commontk_plugingenerator_core.exp
23>qrc_org_commontk_metatype_manifest.cpp
23>Generating Code...
20>org_commontk_plugingenerator_core.vcxproj -> E:\CodeProjects\CTK\CTK-git\CTK_build\bin\Debug\liborg_commontk_plugingenerator_core.dll
4>ctkSettingsDialog.cpp
23>   Creating library E:/CodeProjects/CTK/CTK-git/CTK_build/bin/Debug/org_commontk_metatype.lib and object E:/CodeProjects/CTK/CTK-git/CTK_build/bin/Debug/org_commontk_metatype.exp
23>ctkMetaTypeActivator.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl QLinkedListData::QLinkedListData(void)" (__imp_??0QLinkedListData@@QEAA@XZ) referenced in function "private: class QLinkedList<class ctkServiceReference>::iterator __cdecl QLinkedList<class ctkServiceReference>::detach_helper2(class QLinkedList<class ctkServiceReference>::iterator)" (?detach_helper2@?$QLinkedList@VctkServiceReference@@@@AEAA?AViterator@1@V21@@Z)
23>ctkMTLogTracker.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl QLinkedListData::QLinkedListData(void)" (__imp_??0QLinkedListData@@QEAA@XZ)
23>E:\CodeProjects\CTK\CTK-git\CTK_build\bin\Debug\liborg_commontk_metatype.dll : fatal error LNK1120: 1 unresolved externals
4>ctkSettingsPanel.cpp
23>Done building project "org_commontk_metatype.vcxproj" -- FAILED.
4>ctkSignalMapper.cpp`

So how can I solve this problem? Thanks in advance.

P.S. My build envrionment is VS2019(version 16.7.2 with MSVC2017 14.27.29110), Qt 5.12.4 (with MSVC2017), CTK-master clone from the github.
I have upload the cmakelists and the full output text of VS2019.
[vs2019_output_compile_ctk_20200913.txt](https://github.com/commontk/CTK/files/5213715/vs2019_output_compile_ctk_20200913.txt)

[CMakeLists.txt](https://github.com/commontk/CTK/files/5213713/CMakeLists.txt)

**Comment by al-sabr** [comment]
The solution for this issues is mentioned here : https://forum.qt.io/topic/117230/qlinkedlist-undefined-external-symbol

**Comment by renyuhuiharrison** [comment]
> The solution for this issues is mentioned here : https://forum.qt.io/topic/117230/qlinkedlist-undefined-external-symbol

Thank you for your reply. Maybe I should choose Visual Studio 2017 compiler.

**Comment by lassoan** [comment]
True. When Qt-5.12 was released then VS2019 did not exist, so it was not possible to make Qt-5.12 compatible with VS2019.

In general, you cannot use an old version of a library with a future version of a build toolchain.

 See Qt documentation for build tools compatibility, for example:
https://doc.qt.io/qt-5.12/windows.html
https://doc.qt.io/qt-5.15/windows.html
