### ISSUE TITLE
cmake generate vs program have no souce code olny cmake rules ?

### ISSUE THREAD

**Issue by wubo2018** [commontk/CTK#931]
![image](https://user-images.githubusercontent.com/51027354/93784924-1b1a7480-fc60-11ea-974b-592237560d1b.png)

cmake generate vs program have no souce code olny cmake rules ?
how to generate vs program with souce code ?

**Comment by lassoan** [comment]
This all looks good. You opened the top-level build, which uses rules to download and build all dependencies (VTK, ITK, DCMTK, ...). You first need to build this solution.

Then, after build is completed, if you want to see source code in the solution then open the corresponding solution file within `...-build` subfolder.

**Comment by wubo2018** [comment]
you mean first build  all_build project   then  i can see the source code in  build dir ,  I want to debug it  with vs, how can i do?   thank you

**Comment by lassoan** [comment]
To debug, open the corresponding solution file within ...-build subfolder.

**Comment by wubo2018** [comment]
thank you very much
