### ISSUE TITLE
QtSOAP cannot compile even after changing project settings to lower version for toolset.

### ISSUE THREAD

**Issue by al-sabr** [commontk/CTK#933]
I tried to compile CTK again with CTK_BUILD_ALL_PLUGINS turned on but unfortunately QtSOAP fails.

Although I tried to apply this https://github.com/commontk/CTK#build-instructions with lower toolset version it seems that it doesn't apply at all for QtSOAP.

Qt version : 5.12

I will now try to install 5.15.1 to check if this will resolve that simple build I am trying to run.

**Comment by al-sabr** [comment]
That workaround is only concerning the PluginFramework and not as a general workaround. It would be good to mention it in the build instructions.

Installing Qt version 5.15.1 allowed to compile QtSOAP.

**Comment by lassoan** [comment]
Using Qt version with the supported build toolset is always recommended (even if in some cases incompatibility does not lead to build errors).
