### ISSUE TITLE
Using CPM as a dependency manager for complicated project structure.

### ISSUE THREAD

**Issue by al-sabr** [commontk/CTK#935]
I my process of learning and understanding CMake I've stumbled upon this project that I think might interest the CMake architects if CTK.
 
https://github.com/TheLartians/CPM.cmake

**Comment by lassoan** [comment]
Thanks for sharing. This is an interesting tool and I can see how it can be useful for small projects, when you never modify external projects, you always use the same toolchain and build options for an external project, and all the external projects that you want to use have high-quality CMake build system.

However, in larger applications where CTK is used (3D Slicer, MITK, etc.), using CPM would be way too limiting and having one more layer of abstraction would make build system debugging much harder.

**Comment by lassoan** [comment]
Anybody can still add comments on this, but I'm closing the issue, as no follow-up action is needed.
