### ISSUE TITLE
Is there any document for CTK? The official link can't be opened

### ISSUE THREAD

**Issue by softempire** [commontk/CTK#937]
https://commontk.org/docs/html/modules.html

**Comment by jcfr** [comment]
Thanks for the note and our apology for following only now.

Website https://commontk.org/ is up and running

I reached out to our sysadmin and I will follow up when I hear back.

**Comment by che85** [comment]
Seems that this is still the case. Is there any other documentation available?

**Comment by PaulMartinMurphy** [comment]
I saw this thread after submitting another issue.

**Comment by lassoan** [comment]
Although documentation can be easily generated locally (and it just exposes .h file contents anyway) it would still be nice to be able to browse the documentation online.

**Comment by jamesobutler** [comment]
Closing this as a duplicate of https://github.com/commontk/CTK/issues/919
