### ISSUE TITLE
Integrating KWSys & VNL+VCL into CTK as external libraries

### ISSUE THREAD

**Issue by al-sabr** [commontk/CTK#949]
Greetings

I would like to be able to use KWSys inside of CTK as a submodule can someone guide toward achieving my goal?

Best Regards

**Comment by jcfr** [comment]
To better understand, could you indicate what you are trying to achieve ? 

Without more details, I suggest to use Qt built-in features instead of adding a dependencies to kwsys.

If you have ITK or VTK based classes, `kwsys` is available as `itksys` or `vtksys`

**Comment by al-sabr** [comment]
I tried to use ITK which has kwsys but it doesn't download at all it gets stucked.

```
2>
2>  fatal: clone of 'git://itk.org/ITKData.git' into submodule path 'G:/programming/cpp/CTK/build/ITK/Testing/Data' failed
2>  Failed to clone 'Testing/Data'. Retry scheduled
2>  Cloning into 'G:/programming/cpp/CTK/build/ITK/Testing/Data'...
2>  fatal: unable to connect to itk.org:
2>  itk.org[0: 66.194.253.19]: errno=Invalid argument
2>
2>  fatal: clone of 'git://itk.org/ITKData.git' into submodule path 'G:/programming/cpp/CTK/build/ITK/Testing/Data' failed
2>  Failed to clone 'Testing/Data' a second time, aborting
2>  CMake Error at ITK-cmake/tmp/ITK-gitclone.cmake:52 (message):
2>    Failed to update submodules in: 'G:/programming/cpp/CTK/build/ITK'
2>
```

**Comment by al-sabr** [comment]
Actually I am trying to make a custom version of CTK without ITK & VTK but I still need KWSys. I want to learn how to be able to integrate external projects which I am depending on inside of CTK so that it gets recognized with library linking.

**Comment by jcfr** [comment]
It turns out that ITK external project in CTK is obsolete (see https://github.com/commontk/CTK/blob/master/CMakeExternals/ITK.cmake).

In practice, we build CTK passing `-DITK_DIR:PATH=/path/to/ITK-build` and do not rely on CTK building its own ITK

**Comment by al-sabr** [comment]
I want to remove from CTK all ITK & VTK and unnecessary components.

**Comment by jcfr** [comment]
Since most of the functionalities of kwsys are available through Qt, I don't think it makes sense to integrate it. 

Few options:
* In the Blueberry Framework project, you could add a dependency to CTK, KWSys and VTK.
* or add a file called `CMakeExternals/KWSys.cmake` in your fork of CTK.

**Comment by al-sabr** [comment]
This is the file I added like you mentioned:

```
#
# ZMQ
#


set(proj KWSys)


set(${proj}_DEPENDENCIES "")


ExternalProject_Include_Dependencies(${proj}
  PROJECT_VAR proj
  DEPENDS_VAR ${proj}_DEPENDENCIES
  EP_ARGS_VAR ${proj}_EXTERNAL_PROJECT_ARGS
  USE_SYSTEM_VAR ${CMAKE_PROJECT_NAME}_USE_SYSTEM_${proj}
  )


if(${CMAKE_PROJECT_NAME}_USE_SYSTEM_${proj})
  message(FATAL_ERROR "Enabling ${CMAKE_PROJECT_NAME}_USE_SYSTEM_${proj} is not supported !")
endif()


# Sanity checks
if(DEFINED KWSys_DIR AND NOT EXISTS ${ZMQ_DIR})
  message(FATAL_ERROR "KWSys_DIR variable is defined but corresponds to non-existing directory")
endif()


if(NOT DEFINED KWSys_DIR)


  set(revision_tag d2c2f96b49ed3835a47e)
  if(${proj}_REVISION_TAG)
    set(revision_tag ${${proj}_REVISION_TAG})
  endif()


  set(location_args )
  if(${proj}_URL)
    set(location_args URL ${${proj}_URL})
  elseif(${proj}_GIT_REPOSITORY)
    set(location_args GIT_REPOSITORY ${${proj}_GIT_REPOSITORY}
                      GIT_TAG ${revision_tag})
  else()
    set(location_args GIT_REPOSITORY "${EP_GIT_PROTOCOL}://gitlab.kitware.com/utils/kwsys.git"
                      GIT_TAG ${revision_tag})
  endif()


  ExternalProject_Add(${proj}
    ${${proj}_EXTERNAL_PROJECT_ARGS}
    SOURCE_DIR ${CMAKE_BINARY_DIR}/${proj}
    BINARY_DIR ${proj}-build
    PREFIX ${proj}${ep_suffix}
    ${location_args}
    INSTALL_COMMAND ""
    CMAKE_CACHE_ARGS
      ${ep_common_cache_args}
      #-DKWSYS_NAMESPACE:STRING=itksys
     DEPENDS
      ${${proj}_DEPENDENCIES}
    )
  set(KWSys_DIR ${CMAKE_BINARY_DIR}/${proj}-build)


else()
  ExternalProject_Add_Empty(${proj} DEPENDS ${${proj}_DEPENDENCIES})
endif()


mark_as_superbuild(
  VARS KWSys_DIR:PATH
  LABELS "FIND_PACKAGE"
  )
```

How do I use this in my code ?

**Comment by jcfr** [comment]
Then,  you need to introduce the dependency to KWSys in your library like it is done here: https://github.com/commontk/CTK/blob/master/Libs/Visualization/VTK/Widgets/target_libraries.cmake

**Comment by jcfr** [comment]
Here is a pull request updating the version of ITK along with few other tweaks, see https://github.com/commontk/CTK/pull/951 

In the pull request I linked, looking at what was done to removed older project like ZMQ should help you understand what need to be done to add KWSys ...

**Comment by al-sabr** [comment]
I was able to add KWSys & VXL(vnl,vcl) but I get to a point where the linking doesn't work with your method:

You can check what I did for the last 3 commits. https://github.com/al-sabr/CTK/commits/ctk-blueberry-port-from-mitk

```
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkObjectFactoryBase.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\Libs\itk\itkDirectory.h(22,10): fatal error C1083: Cannot open include file: 'itksys/Directory.hxx': No such file or directory [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkDataObject.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkThreadPool.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\Libs\itk\itkThreadPool.cxx(21,10): fatal error C1083: Cannot open include file: 'kwsys/SystemTools.hxx': No such file or directory [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkMultiThreaderBase.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\Libs\itk\itkVector.h(23,10): fatal error C1083: Cannot open include file: 'vnl/vnl_vector_ref.h': No such file or directory [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkRealTimeStamp.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkMath.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\Libs\itk\itkMath.h(34,10): fatal error C1083: Cannot open include file: 'vnl/vnl_math.h': No such file or directory [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkNumericTraitsPointPixel.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\Libs\itk\itkVector.h(23,10): fatal error C1083: Cannot open include file: 'vnl/vnl_vector_ref.h': No such file or directory [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkVector.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\Libs\itk\itkVector.h(23,10): fatal error C1083: Cannot open include file: 'vnl/vnl_vector_ref.h': No such file or directory [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkVersion.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkBuildInformation.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkPlatformMultiThreader.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\Libs\itk\itkVector.h(23,10): fatal error C1083: Cannot open include file: 'vnl/vnl_vector_ref.h': No such file or directory [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkImageSourceCommon.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\Libs\itk\itkVector.h(23,10): fatal error C1083: Cannot open include file: 'vnl/vnl_vector_ref.h': No such file or directory [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkImageRegionSplitterBase.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\Libs\itk\itkVector.h(23,10): fatal error C1083: Cannot open include file: 'vnl/vnl_vector_ref.h': No such file or directory [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkImageIORegion.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\Libs\itk\itkVector.h(23,10): fatal error C1083: Cannot open include file: 'vnl/vnl_vector_ref.h': No such file or directory [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkImageRegionSplitterSlowDimension.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\Libs\itk\itkVector.h(23,10): fatal error C1083: Cannot open include file: 'vnl/vnl_vector_ref.h': No such file or directory [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkProcessObject.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\Libs\itk\itkVector.h(23,10): fatal error C1083: Cannot open include file: 'vnl/vnl_vector_ref.h': No such file or directory [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkDirectory.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\Libs\itk\itkDirectory.h(22,10): fatal error C1083: Cannot open include file: 'itksys/Directory.hxx': No such file or directory [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkNumericTraitsVectorPixel.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\Libs\itk\itkVector.h(23,10): fatal error C1083: Cannot open include file: 'vnl/vnl_vector_ref.h': No such file or directory [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    itkProgressReporter.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>    Generating Code...
4>    Compiling...
4>    itkPoolMultiThreader.cxx
4>  G:\programming\cpp\CTK\Libs\itk\itkMacro.h(1142,1): warning C4005: 'ITK_EXPORT': macro redefinition [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\build\CTK-build\Libs\itk\itkExport.h(18): message : see previous definition of 'ITK_EXPORT' [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
4>  G:\programming\cpp\CTK\Libs\itk\itkVector.h(23,10): fatal error C1083: Cannot open include file: 'vnl/vnl_vector_ref.h': No such file or directory [G:\programming\cpp\CTK\build\CTK-build\Libs\itk\CTKitk.vcxproj]
```

**Comment by al-sabr** [comment]
Missing elements in Visual Studio 2019 Project Property Pages

![](https://user-images.githubusercontent.com/26530975/107428204-95ba3280-6b22-11eb-9670-e313a7a014af.png)

![](https://user-images.githubusercontent.com/26530975/107428257-a9659900-6b22-11eb-8099-6054e5123434.png)

**Comment by jcfr** [comment]
> re: ITK error

The current version used in CTK is old, consider re-basing on top of https://github.com/commontk/CTK/pull/951

**Comment by al-sabr** [comment]
How can I achieve your advice?

**Comment by jcfr** [comment]
I noticed that the following library have been added to your topic, I would suggest to remove these:

* https://github.com/al-sabr/CTK/tree/f7c8c98630a86db70b349ef49c53e3a675748b49/Libs/itk

* https://github.com/al-sabr/CTK/tree/f7c8c98630a86db70b349ef49c53e3a675748b49/Libs/mbilog

* https://github.com/al-sabr/CTK/tree/f7c8c98630a86db70b349ef49c53e3a675748b49/Libs/mitk

> re: qtsingleapplication (https://github.com/al-sabr/CTK/tree/f7c8c98630a86db70b349ef49c53e3a675748b49/Libs/qtsingleapplication)

This one should probably be contributed in its own CTK pull request or we could re-assess if it is really needed. Reading this post was informative: https://stackoverflow.com/questions/17937618/how-to-use-qtsingleapplication#17937747

Last, since there is a maintained project for Qt5 and Qt6, I would prefer we use this instead of maintaining our own .... https://github.com/itay-grudev/SingleApplication

**Comment by jcfr** [comment]
> Am I linking the wrong target names or what?

Sadly, I do not have the bandwidth to review in details.

That said, there are few red flags to address:

* A Library called `itk` inside CTK should probably not be added. May be useful classes could be contributed to upstream ITK or to an independent ITK module (see https://itk.org/ITKSoftwareGuide/html/Book1/ITKSoftwareGuide-Book1ch9.html#x50-1430009)
* The namespace associated with KWSys should not be `itksys` as it is "reserved" for ITK project. We should really avoid KWSys as a dependency.
* Adding VNL as a direct dependency is likely out of the scope of CTK

The plugins living in the `Plugins` directory of CTK are expected to be CTK plugins, your branch integrates a different flavor of  plugins following the "blueberry" paradigm. 

It may be worth to step back and try to understand the following:
* What is the current usage of the CTK plugins infrastructure ? my understanding is that it was intended to be used in MITK (@nolden may be able to comment further)
* Is there a way to work on a roadmap where we would deprecate (or update) CTK plugins ? I really would like to avoid having to maintain multiple plugin mechanism.

cc: @pieper @lassoan @nolden

**Comment by saschazelzer** [comment]
Hi,

this being somewhat my legacy, I feel the urge to comment here.

BlueBerry plugins *are* CTK plugins. They have some additional CMake
helpers if I remember correctly, and additional dependencies to other
BlueBerry plugins.

I believe it would be fair to mark the CTK Plugin Framework as "not
maintained" and depending on the external usage (if there is any data
about that at all), the plugin framework could be deprecated and
eventually removed from CTK. People could be pointed to CppMicroServices
for an alternative (it lacks some plugins present in CTK though).

Years ago, I was playing with the idea to make the CTK PluginFramework
use CppMicroServices under the hood. The CTK part would then act as a
compatibility layer to ease the transition to CppMicroServices.
Obviously, this never happened.

Best,
Sascha

**Comment by al-sabr** [comment]
@jcfr My goal right now is to modularize the CTKitk to get rid of ITK in its whole, What you are suggesting I will consider for the next stages but I only want to be able to have my CTK, PluginFramework, Blueberry & my Workspace so that I can start to build my app.

This is my last compilation error and I am not compiling anything which is depending on ITK neither VTK.

I didn't activated the ImageProcessing library or Vizualisation library.

As I said I want to remove any Libs or Apps or Plugins which are DMTK ITK VTK or any other TK dependant ending libraries.

Is there any bug with the handling of external dependencies by CTK for the following?

```
set(target_libraries
  KWSYS_LIBRARIES
  VXL_LIBRARIES
  ITKSYS_LIBRARIES
  VCL_LIBRARIES VNL_LIBRARIES
  CTKCore
)
```

**Comment by jcfr** [comment]
> BlueBerry plugins *are* CTK plugins. [...]  CTK Plugin Framework as "not maintained" [...] People could be pointed to CppMicroServices

@saschazelzer  Thanks for your input, this is really helpful and informative.

**Comment by jcfr** [comment]
> Is there any bug with the handling of external dependencies by CTK for the following?

@al-sabr 

The following file should be updated as well: https://github.com/al-sabr/CTK/blob/f7c8c98630a86db70b349ef49c53e3a675748b49/CMake/ctkBlockCheckDependencies.cmake#L64-L113

**Comment by al-sabr** [comment]
I am now having errors from CMake:

```
CMake Error at CMakeLists.txt:1164 (find_package):
4>    By not providing "FindKWSYS.cmake" in CMAKE_MODULE_PATH this project has
4>    asked CMake to find a package configuration file provided by "KWSYS", but
4>    CMake did not find one.
4>
4>    Could not find a package configuration file provided by "KWSYS" with any of
4>    the following names:
4>
4>      KWSYSConfig.cmake
4>      kwsys-config.cmake
4>
4>    Add the installation prefix of "KWSYS" to CMAKE_PREFIX_PATH or set
4>    "KWSYS_DIR" to a directory containing one of the above files.  If "KWSYS"
4>    provides a separate development package or SDK, be sure it has been
4>    installed.
4>
```

**Comment by al-sabr** [comment]
I really don't know what to do yet! I am out of options ...

**Comment by jcfr** [comment]
Since the `itk` part of blueberry project already depends on `itksys` (see [here](https://github.com/al-sabr/CTK/blob/ad0546fbaa91bf31f9d6e0f9df5ec61b06cf305c/Libs/itk/itkMultiThreaderBase.cxx#L37-L38)), you should not have to include the `FindKWSys.cmake`. Instead, you should have to configure KWSys so that it generate the `itksys` namespace. See [here](https://gitlab.kitware.com/utils/kwsys/-/blob/dda7a943856ad22e374a9b0434727285461770a6/CMakeLists.txt#L14) 

But again, all files in the itk library of blueberry are already maintained in ITK itself, if you compile ITK statically ... it would have a very low footprint and likely achieve the same thing.

**Comment by al-sabr** [comment]
As you can see here I initialized the namespace:

al-sabr@a523ed3

**Comment by al-sabr** [comment]
@jcfr I tried your suggestion with ITK at the end and still it doesn't work:

![](https://user-images.githubusercontent.com/26530975/107569805-04fa5a00-6be9-11eb-8eec-80acac30abd8.png)

![](https://user-images.githubusercontent.com/26530975/107569874-16436680-6be9-11eb-8d08-73f17dae49d6.png)

**Comment by jcfr** [comment]
> I tried your suggestion with ITK at the end and still it doesn't work:

Thanks for moving in that direction, removing the copy of ITK files and using the official built statically is the most sustainable path forward.

Now, to address the issue regarding the static build of ITK. Could you post the options you used to configure it on the ITK forum. See https://discourse.itk.org/.

You post should include step for reproducing the problem using instructions like these where you will use correct values instead of placeholders:

```text
git clone ...
cmake -G "" -A "" -DOPT1:STRING= .... 
cmake --build C:\path\to\build --config Release -- /maxcpucount:8
```

**Comment by jcfr** [comment]
It also looks like the `CTKmitk` library is not calling `find_package(ITK COMPONENTS NameOfComponent1 ... REQUIRED)` ...

**Comment by al-sabr** [comment]
This is the full log : https://pastebin.com/RRxxNci2

**Comment by dzenanz** [comment]
The first error is this:
```text
gdcmSystem.cxx
2>  G:\programming\cpp\CTK\build\ITK\Modules\ThirdParty\GDCM\src\gdcm\Source\Common\gdcmSystem.cxx(812,3): error C3861: 'gettimeofday''rusage' uses undefined struct 'rusage' [G:\programming\cpp\CTK\build\ITK-build\Modules\ThirdParty\HDF5\src\itkhdf5\src\hdf5-static.vcxproj]
2>  G:\programming\cpp\CTK\build\ITK\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5timer.c(126,5): error C2065: 'RUSAGE_SELF': undeclared identifier [G:\programming\cpp\CTK\build\ITK-build\Modules\ThirdParty\HDF5\src\itkhdf5\src\hdf5-static.vcxproj]
2>  G:\programming\cpp\CTK\build\ITK\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5timer.c(127,35): error C2224: left of '.ru_utime' must have struct/union type [G:\programming\cpp\CTK\build\ITK-build\Modules\ThirdParty\HDF5\src\itkhdf5\src\hdf5-static.vcxproj]
2>  G:\programming\cpp\CTK\build\ITK\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5timer.c(128,36): error C2224: left of '.ru_utime' must have struct/union type [G:\programming\cpp\CTK\build\ITK-build\Modules\ThirdParty\HDF5\src\itkhdf5\src\hdf5-static.vcxproj]
2>  G:\programming\cpp\CTK\build\ITK\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5timer.c(129,35): error C2224: left of '.ru_stime' must have struct/union type [G:\programming\cpp\CTK\build\ITK-build\Modules\ThirdParty\HDF5\src\itkhdf5\src\hdf5-static.vcxproj]
2>  G:\programming\cpp\CTK\build\ITK\Modules\ThirdParty\HDF5\src\itkhdf5\src\H5timer.c(130,36): error C2224: left of '.ru_stime' must have struct/union type [G:\programming\cpp\CTK\build\ITK-build\Modules\ThirdParty\HDF5\src\itkhdf5\src\hdf5-static.vcxproj]
```
I don't remember seeing this error before. Is this coming from GDCM, HDF5, or somehow their interaction?

**Comment by al-sabr** [comment]
Look at the screenshots it is detailed.

**Comment by al-sabr** [comment]
What do you think the problem is !

**Comment by al-sabr** [comment]
Is there any one who still reading this ticket ?

**Comment by dzenanz** [comment]
When compiling ITK, you can turn off a CMake setting `ITK_BUILD_DEFAULT_MODULES`, then you will be able to turn on and off modules per group. If you turn of a group, then you will be able to turn on/off individual modules from that group. Use CMake-GUI to experiment with this to figure out which settings you need to pass to ITK in superbuild to turn off GDCM.

**Comment by al-sabr** [comment]
What are the basic low footprint required modules for ITK to compile with KWSys & VXL

**Comment by dzenanz** [comment]
Only `ITKCommon` (the base module). It depends on VNL and KWSys, I belive.

**Comment by al-sabr** [comment]
Is there any kind of setting for basic compile ?

**Comment by dzenanz** [comment]
Disable all modules except ITKCommon, and use default settings for the rest?

**Comment by al-sabr** [comment]
There is no other options even when I created a variable in CMake with ITK\_BUILD\_DEFAULT\_MODULES = OFF.

**Comment by al-sabr** [comment]
I found this blog post concerning ITK and settings : https://blog.kitware.com/advance-itk-with-modules/

**Comment by al-sabr** [comment]
Trying to move basic KWSys & VXL in independant module : InsightSoftwareConsortium/ITK#2298

**Comment by thewtex** [comment]
> But what is weird is that in CTK no ITK_BUILD_DEFAULT_MODULES is appearing to be deactivated in the CMake GUI.

@al-sabr since this is a *SuperBuild*, i.e. a CMake build that coordinates the build of other projects, options are only available for the *SuperBuild* in the CMake GUI, not the component projects, e.g. ITK.

**Comment by al-sabr** [comment]
The integration was successfully completed with a custom ITK version that I need to work a little bit more on so that it doesn't break Core/Common.

**Comment by dzenanz** [comment]
A bit longer explanation is given here: https://github.com/InsightSoftwareConsortium/ITK/issues/2325#issuecomment-780978689. This issue can be closed.
