### ISSUE TITLE
Move PatientAge to study level

### ISSUE THREAD

**Issue by nolden** [commontk/CTK#95]
In code and database schema.

**Comment by jcfr** [comment]
Since this issue hasn't been updated in year, I suggest we close it.

Cc: @pieper  @lassoan @nolden

**Comment by pieper** [comment]
Yes, let's close it.  This hasn't turned into a big issue.

**Comment by lassoan** [comment]
DICOM browser needs major overhaul, as several essential fields are missing, some of the currently displayed fields are not commonly needed, and in general the fields display is not configurable enough.

It would be nice to have a place to capture these fix and improvement ideas. If we don't want to have several small issues then we can have one where we include all. We could make this issue more general or close this one and open a new one for the general rework of the component.

**Comment by jcfr** [comment]
Closing.

* Performance and usability of the DICOM browser have been improved in https://github.com/commontk/CTK/pull/886 
* Use of display tables to allow showing derived and custom columns in DICOM browser added in https://github.com/commontk/CTK/pull/858
