### ISSUE TITLE
ITK is not found when CMake is trying to download the repo thus compilation errors 

### ISSUE THREAD

**Issue by al-sabr** [commontk/CTK#962]
```
2>  Creating directories for 'ITK'
2>  Performing download step (git clone) for 'ITK'
2>  Cloning into 'ITK'...
2>  fatal: repository 'https://itk.org/ITK.git/' not found
2>  Cloning into 'ITK'...
2>  fatal: repository 'https://itk.org/ITK.git/' not found
2>  Cloning into 'ITK'...
2>  fatal: repository 'https://itk.org/ITK.git/' not found
2>  -- Had to git clone more than once:
2>  CMake Error at ITK-cmake/tmp/ITK-gitclone.cmake:31 (message):
2>    Failed to clone repository: 'https://itk.org/ITK.git'
```

**Comment by jamesobutler** [comment]
This is evidence of an old ITK being used if building the CTK superbuild. I would suggest you review the changes proposed in #951 which updates ITK from `v3.21.1` using https://itk.org/ITK.git, versus `v5.1.2` using https://github.com/InsightSoftwareConsortium/ITK.

**Comment by al-sabr** [comment]
Tried  to test if compiling a standalone version works out of the box but it seems that it is not a good idea to upgrade the version.

InsightSoftwareConsortium/ITK#2502
