### ISSUE TITLE
assert crash on mac - fail to access listView in dialog

### ISSUE THREAD

**Issue by pieper** [commontk/CTK#980]
When I try to select a directory in the DICOM import dialog I get this assert:

```
ASSERT: "listView" in file /opt/s/CTK/Libs/Widgets/ctkFileDialog.cpp, line 102
error: [/opt/s/Slicer-build/bin/Slicer.app/Contents/MacOS/./Slicer] exit abnormally - Report the problem.
```
With the stack trace that follows.

This is probably related to https://github.com/commontk/CTK/commit/c4f1eeead234022e74de978126e3a54f648880e5 and https://github.com/commontk/CTK/commit/5532a5a7ec07fada320cda43b831515d702a1c6f

@jamesobutler could you see if this logic needs to be updated for native dialogs?

```
2   libsystem_c.dylib             	0x00007fff20290411 abort + 120
3   org.qt-project.QtCore         	0x0000000104533b39 0x10451b000 + 101177
4   org.qt-project.QtCore         	0x000000010486172e QMessageLogger::fatal(char const*, ...) const + 196
5   org.qt-project.QtCore         	0x0000000104860e76 qt_assert(char const*, char const*, int) + 67
6   libCTKWidgets.0.1.0.dylib     	0x00000001031a50c8 ctkFileDialogPrivate::listView() const + 152 (ctkFileDialog.cpp:102)
7   libCTKWidgets.0.1.0.dylib     	0x00000001031a5e2e ctkFileDialog::clearSelection() + 46 (ctkFileDialog.cpp:224)
8   libCTKDICOMWidgets.0.1.0.dylib	0x000000010303cb30 ctkDICOMBrowser::onImportDirectoriesSelected(QStringList) + 112 (ctkDICOMBrowser.cpp:913)
9   libCTKDICOMWidgets.0.1.0.dylib	0x000000010307cf1f ctkDICOMBrowser::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) + 1407 (moc_ctkDICOMBrowser.cpp:343)
10  org.qt-project.QtCore         	0x0000000104732182 0x10451b000 + 2191746
11  org.qt-project.QtWidgets      	0x0000000103b88312 QFileDialogPrivate::_q_emitUrlsSelected(QList<QUrl> const&) + 386
12  org.qt-project.QtWidgets      	0x0000000103b8751a QFileDialog::accept() + 90
13  libCTKWidgets.0.1.0.dylib     	0x00000001031a65b6 ctkFileDialog::accept() + 758 (ctkFileDialog.cpp:302)
```

**Comment by jamesobutler** [comment]
As related to https://github.com/Slicer/Slicer/issues/5739, does the native file dialog actually open on macOS when using this dialog as part of the DICOM browser? The information in that other issue seemed to indicate that it was crashing on opening the dialog used for selecting. Or does it actually only crash upon selection and closing of the native dialog as being indicated in your trace stack?

**Comment by pieper** [comment]
I can make it show up if I remove the "ApplicationModal" option, but the position is inconsistent [as in my note on discourse](https://discourse.slicer.org/t/slicer-is-freezing-on-macos-when-clicking-on-import-dicom-files/18624/12).

Once I get the dialog to appear then I get this crash.
