### ISSUE TITLE
CMake Error at CMake/ctkMacroSetupQt.cmake:87

### ISSUE THREAD

**Issue by wuExin** [commontk/CTK#986]
I was trying to build CTK on windows10.
Then I got error:
Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
Found unsuitable Qt version "5.15.2" from C:/Qt/5.15.2/msvc2019_64/bin/qmake.exe
CMake Error at CMake/ctkMacroSetupQt.cmake:87 (message):
  error: Qt4 was not found on your system.  You probably need to set the
  QT_QMAKE_EXECUTABLE variable
Call Stack (most recent call first):
  CMakeLists.txt:423 (ctkMacroSetupQt)

OS: windows10
Visual studio: 2019
QT: Qt 5.15
CMake: 3.19.2

**Comment by feifeizuo** [comment]
Just change CTK_QT_VERSION 4 to 5 in CMake GUI or *.cmake file.

**Comment by gyongchae** [comment]
> Just change CTK_QT_VERSION 4 to 5 in CMake GUI or *.cmake file.

Thanks to you, I solved it by simply changing it to set(CTK_QT_VERSION "5" CACHE STRING "Expected Qt version") in ctkMacroSetupQt.cmake file.
