### ISSUE TITLE
Build ctk with qt5.9 problem

### ISSUE THREAD

**Issue by CppPeng** [commontk/CTK#995]
when I use CMake_gui to configure,I meet this problem
"CMake Error at CMake/ctkFunctionCheckoutRepo.cmake:50 (message):
  Building directory F:/H_SourceCode/ctk_9_4/build/PluginsContrib-proj
  failed:
Call Stack (most recent call first):
  CMake/ctkFunctionAddPluginRepo.cmake:16 (ctkFunctionCheckoutRepo)
  CMakeLists.txt:712 (ctkFunctionAddPluginRepo)"

**Comment by lassoan** [comment]
Could you copy here the entire error message (including the complete call stack)?

**Comment by CppPeng** [comment]
> Could you copy here the entire error message (including the complete call stack)?
... ...
Enabling [CTK_PLUGIN_org.commontk.dah.examplehost] because of [ CTK_APP_ctkExampleHost:1] evaluates to True
Enabling [CTK_PLUGIN_org.commontk.dah.examplehost] because of [CTK_BUILD_ALL_PLUGINS:1] evaluates to True
-- Selecting Windows SDK version 10.0.10586.0 to target Windows 10.0.19042.

-- Configuring done

-- Generating done

-- Build files have been written to: F:/H_SourceCode/ctk_9_4/build/PluginsContrib-proj

Microsoft (R) 生成引擎版本 14.0.25420.1
版权所有(C) Microsoft Corporation。保留所有权利。


  Creating directories for 'PluginsContrib'

  Building Custom Rule F:/H_SourceCode/ctk_9_4/build/PluginsContrib-proj/CMakeLists.txt

  Performing download step (git clone) for 'PluginsContrib'

  Cloning into 'PluginsContrib'...

  fatal: unable to access 'https://github.com/commontk/PluginsContrib.git/': Could not resolve host: github.com

  Cloning into 'PluginsContrib'...

  fatal: unable to access 'https://github.com/commontk/PluginsContrib.git/': Could not resolve host: github.com

  Cloning into 'PluginsContrib'...

  fatal: unable to access 'https://github.com/commontk/PluginsContrib.git/': Could not resolve host: github.com

  -- Had to git clone more than once:

  CMake Error at PluginsContrib-proj/ep/tmp/PluginsContrib-gitclone.cmake:31 (message):

    Failed to clone repository:

    'https://github.com/commontk/PluginsContrib.git'
  

            3 times.

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: “cmd.exe”已退出，代码为 1。 [F:\H_SourceCode\ctk_9_4\build\PluginsContrib-proj\PluginsContrib.vcxproj]

CMake Error at CMake/ctkFunctionCheckoutRepo.cmake:50 (message):
  Building directory F:/H_SourceCode/ctk_9_4/build/PluginsContrib-proj
  failed:
Call Stack (most recent call first):
  CMake/ctkFunctionAddPluginRepo.cmake:16 (ctkFunctionCheckoutRepo)
  CMakeLists.txt:712 (ctkFunctionAddPluginRepo)


Configuring incomplete, errors occurred!
See also "F:/H_SourceCode/ctk_9_4/build/CMakeFiles/CMakeOutput.log".

**Comment by lassoan** [comment]
I would recommend to keep CTK_USE_CONTRIBUTED_PLUGINS=OFF. You don't need it, unless you specifically want to use CTK to interface with XNAT.

**Comment by CppPeng** [comment]
> I would recommend to keep CTK_USE_CONTRIBUTED_PLUGINS=OFF. You don't need it, unless you specifically want to use CTK to interface with XNAT.

OK.Thanks a lot.
